### ISSUE TITLE
Map California water balance data into WaDE 2.0

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#10]
ftp://mae2.sdsc.edu/published/

This link is for 2015 data and metadata as an example to start with.
ftp://mae2.sdsc.edu/published/CA-DWR-WaterBalance_20190505_CA-DWR-WaterBalance-2015-md56acf731afc6d5fa24c5fce506b24c877.zip

Here is an example of data that was mapped into WaDE 1.0. Not sure why it is not working
http://www.westernstateswater.org/CentralCatalog/WADE/v0.2/GetCatalog/GetCatalog.php?loctype=REPORTUNIT&loctxt=508&orgid=ALL&state=49

**Comment by tsga** [comment]
Aggregated amounts import works. Done for 2011 to 2015

**Comment by amabdallah** [comment]
Update source of data to this 
https://data.cnra.ca.gov/dataset/water-plan-water-balance-data

**Comment by rwjam** [comment]
CDWR would like to see WaDE data aggregation cross-checks to verify the mapping between DWR vocabularies and WaDE terms.
