### ISSUE TITLE
New Mexico Public Water Supply areas

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#100]
This shapefile will probably be used as POU for site-specific water use data in NM. I'll ask NM if they have time-series data that goes with it
https://catalog.newmexicowaterdata.org/dataset/public-water-supply-areas

This POU shapefile seems to also have diverted (withdrawn) annual water amount in each POU per water sources type but just for 2010 and 2015. Let's try to import it to WaDE and see how it fits in RShiny. Then I'll reach out to the NM folks and ask if they have monthly data or for the rest of the years.

**Comment by rwjam** [comment]
The Public Water Suppliers (PWS) shapefiles are a data set of non-transient PWS locations, their associated service areas, and the locations of their supply sources.

Going through the file and metadata, does look like it suppose to have estimated amount of surface water & groundwater diverted by the PWS, but all the values are 0.

![image](https://user-images.githubusercontent.com/17555073/174151281-4a9526fb-1473-4605-9c9c-c64d07e73ac0.png)

**Comment by rwjam** [comment]
similar issue to this, will close for now: https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/issues/45
