### ISSUE TITLE
Map Delaware River Basin historic water use data to WaDE

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#101]
We have a commitment under the IOW BHP grant to explore including eastern states' water data into WaDE.

The Delaware River Basin Commission has just released this report along with their water use dataset.
https://www.nj.gov/drbc/programs/supply/use-demand-projections2060.html

Please download the dataset (Excel) and GIS maps. The Excel file appears to have great metadata. We're only interested in historic data so let's ignore the projections for future years. 
One key difference I noticed is the used unit which is MGD which probably needs to be converted to volume. We'd need to meet up with the commission folks but after we have a good chance to understand their data and how it fits into WaDE so we can ask them good questions. 
![image](https://user-images.githubusercontent.com/3268971/138940232-11a8c325-db48-47a6-b228-7e1765808155.png)

**Comment by rwjam** [comment]
(08/25/2022) This is something we may pursue in the future.

**Comment by amabdallah** [comment]
Let's revisit this one this week or early next week so I can report if we're confident it has the needed metadata and we can import it by the end of June 2023

**Comment by rwjam** [comment]
Notes on data

- Download data here (see image).
![image](https://user-images.githubusercontent.com/17555073/228350154-fd0d36c3-aadb-45a3-b7be-9a2cb25e0e4f.png)


- we only want the historic surface water and groundwater data. Which can be found on the following sheets: A-1, A-6, A-9, A-11, A-14, A-17, A-22
- this is withdrawal and consumptive use data
- should be about 147 subbasins.
- can match timeseries data to shapefile via **BASIN_ID** input value.

**Comment by amabdallah** [comment]
Should we close this issue? I believe its done
