### ISSUE TITLE
California-Operated Stream Gages data to WaDE

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#102]
Let's start here. Ignore stations that are operated or their data is accessible through USGS
https://gispublic.waterboards.ca.gov/portal/home/item.html?id=32dfb85bd2744487affe6e3475190093

The actual time series data is available through Geoconnex here (Check with Kyle)
https://sb19.linked-data.internetofwater.dev/

**Comment by amabdallah** [comment]
Kyle has organized CA gage location metadata and put it in Geoconnex.
https://sb19.linked-data.internetofwater.dev/collections/ca_gages/items?startindex=200

Each site has URL pointing to its page on California's system

**Comment by rwjam** [comment]
Unnecessary links, don't use:
- Geoconnex link here: https://sb19.linked-data.internetofwater.dev/
- broken link: http://cdec.water.ca.gov/cgi-progs/staMeta?station_id=YPB
- Individual site info for Site# YPB, but nothing to draw upon: https://cdec.water.ca.gov/dynamicapp/staMeta?station_id=YPB
- custom landing page for some CA gage locations that returns 200 sites.  However, can't adjust that 200 value accurately and get exact number of sites, use shapefile option instead: https://sb19.linked-data.internetofwater.dev/collections/ca_gages/items?startindex=200
-  some historic info maybe, but site doesn't seem to respond: https://wdl.water.ca.gov/waterdatalibrary/ContinuousData.aspx?ReloadData=False

Use these:
- shapefile info here, want **siteid** field, ignore all sites that have a **operator** = USGS: https://gispublic.waterboards.ca.gov/portal/home/item.html?id=32dfb85bd2744487affe6e3475190093
- Use something like this to attach timeseries data to sites.  Attach to each **siteid** value.  We don't know min & max time, so will have to guess for now.  Guessing makes the query take longer, expect to this take some time.: https://cdec.water.ca.gov/dynamicapp/req/CSVDataServlet?Stations=CMR&SensorNums=1&dur_code=E&Start=2020-12-28T00%3A00&End=2022-03-15

**Comment by rwjam** [comment]
May be too many records to retrieve.  Ran into memory issue with script.
![image](https://user-images.githubusercontent.com/17555073/158902236-74d3abba-ae31-4613-82c8-e956a09032ce.png)

**Comment by rwjam** [comment]
Going to use SensorNums=65 and only use sites that have a known timeseries of monthly for now (about 24 sites).  Good place to start.

- Example API: "https://cdec.water.ca.gov/dynamicapp/req/CSVDataServlet?Stations=ERS&SensorNums=65&dur_code=M&Start=1950-03-22&End=2022-03-22"

**Comment by rwjam** [comment]
Going to also include reservoir data level time series data.  Iwas able to literally just copy / paste a site info table from their website.  Looks like we can use that same API call too using a a SensorNums = 15 for monthly RESERVOIR STORAGE, AF.

![image](https://user-images.githubusercontent.com/17555073/159586130-c30367df-eb14-4636-9008-b3c3f33fe71d.png)

- https://cdec.water.ca.gov/dynamicapp/req/CSVDataServlet?Stations=DRE&SensorNums=15&dur_code=M&Start=1950-03-22&End=2022-03-22%22
