### ISSUE TITLE
New California's reported water use (points of diversions)

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#106]
California has published historic monthly water use at diversions points related to their water rights. To start with, let's look into the file 2016-2018 which size is huge ~ 3GB. It crashed on me so I think it only can be opened in Python or R.
https://data.ca.gov/dataset/california-water-rights-water-use-reported

 This data is more comprehensive than the M&I water use data source we imported before but this new one is for PODs only. USGS may love this new monthly dataset. Let's map it into WaDE and see how aligns with what we and USGS want.

**Comment by rwjam** [comment]
- Big files.  Will take time to download.  Can't open in excel, will have to be strictly through code scripts.
- I do see timeseries amount data per values ties to site info.
- This will be another CA ss data set, separate from the existing [Drinking Water - Public Water System](https://data.ca.gov/dataset/drinking-water-public-water-system-annually-reported-water-production-and-delivery-information) set already in WaDE.
