### ISSUE TITLE
Import New Jersey Water Withdrawal, Use, and Return Data (ss) Summaries

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#107]
We used to have New Jersey's data in WaDE 1.0. Part of our deliverables to the BHP grant is to explore adding eastern states. 

Let's look into mapping this data again into WaDE 2.0
https://www.nj.gov/dep/njgs/geodata/dgs10-3.htm

Fun fact, this data is in the Microsoft Access database :)
The good news is that our Microsoft Office comes Access

**Comment by rwjam** [comment]
Meta data for the **3) Use by Site** data.

![image](https://user-images.githubusercontent.com/17555073/151213025-77a9331b-1b39-4e52-8856-f04ac2f4977c.png)

**Comment by rwjam** [comment]
Looking over the available data this morning.  There are 5 different data sets within that link (.e.g, 1) withdrawals by HUC14 drainage basin; 2) withdrawals by municipality; 3) use by site; 4) returns by HUC14 drainage basin; 5) returns by municipality).  As a whole, it’s time series data associated with an area / site (e.g., HUC14, Municipality, permit site). 

**Notes and Comments:**

- It wasn’t clear in the GitHub, but how are we treating this data? Is it site specific?  Is it aggregate?  Is with water rights?  I assume we are treating this like ss data as there is withdrawals and returns data, so we could treat like the UT ss.  However, that is very similar to how we use the agg data, so it’s hard to determine what niche this falls in.  There is also some permit info within the 3) use by site data, so we could squeeze some water right info out of it too.  However, the 3) use by site is a timeseries of volume (MG), so we don’t know the assigned allocated amounts recorded to the permit.

- As a whole, this NJ data is time series data.  Some useful / basic info we can get out of this and fit into WaDE.  However, there is no location info associated with any of this data (i.e., latitude, longitude, polygon).  We’ll need to try and track down a shapefile for either HUC14, NJ municipality areas, or permit sites before we can fully use this data.

**Comment by rwjam** [comment]
Meta data for the **3) Use by Site** data.

![image](https://user-images.githubusercontent.com/17555073/151213025-77a9331b-1b39-4e52-8856-f04ac2f4977c.png)

**Comment by amabdallah** [comment]
**Kent Barr shared this through an email on Jan 27.** Research Scientist at New Jersey Geological and Water Survey 

- You can find the shapefiles you requested and many others at the NJDEP GIS Bureau’s open data page: https://gisdata-njdep.opendata.arcgis.com/

-  HUC 14’s can be found directly at the following link:
https://gisdata-njdep.opendata.arcgis.com/datasets/njdep::14-digit-hydrologic-unit-code-delineations-for-new-jersey/about

 - Municipality Layer:
https://gisdata-njdep.opendata.arcgis.com/datasets/newjersey::municipal-boundaries-of-nj/about

**Steven Domber shared this on Jan 28th:**  Section Chief, Water Supply Modeling and Planning
New Jersey Geological and Water Survey
I agree with your use of the centroid as a location for the withdrawals to provide geographic point to plot on a map. One point to clarify, the two files “DGS10-3-With-Mun.accdb” and “DGS10-3-With-HUC.accdb” contain the same withdrawal sites and volumes, but one uses the HUC14 for a location in lieu of a lat and long and the other the municipality in lieu of a lat and long. The same can be said for the two return files: “DGS10-3-Ret-Mun.accdb” and “DGS10-3-Ret-HUC.accdb”.

**Comment by amabdallah** [comment]
@rwjam So we're more interested in the time-series data that is associated with each municipality (USGS goal).
Since NJ can't share the long. and lat. of sites publically, let's use the centroid of each municipality polygon (and store polygon geometry), I think similar to CA and TX data.  

We will revisit the discussion of how WaDE can protect the real long. and lat coordinates from public access.

**Comment by rwjam** [comment]
We will count this as ss data attached to a municipality area.
