### ISSUE TITLE
Texas Historic Water Use

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#109]
Let's revisit how TWDB describe their water use term. I think it should be "withdrawal". Then let's update the ReadME

https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/tree/master/Texas/AggregatedAmounts

**Comment by rwjam** [comment]
- 2000-2016 Historical Water Use Estimates csv files contained aggregated water budget data and info and were obtained from the provided [TWDB Historical Water Use Estimates](http://www.twdb.texas.gov/waterplanning/waterusesurvey/estimates/index.asp). Each year is separated out into two different area types: Basin and County. Information for each area type can be found in the SumFinal_BasinReport.xlsx and SumFinal_CountyReport.xlsx per year respectively.
- Texas County and Basin shapefiles data retrieved from personal correspondence via email from between the TWDB and the WSWC.
