### ISSUE TITLE
Import Arizona water use data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#11]
https://new.azwater.gov/ama/ama-data

Each active management area has its excel file.

![image](https://user-images.githubusercontent.com/3268971/71199644-a0957200-2253-11ea-8a27-c0f340a46c5e.png)

**Comment by rwjam** [comment]
Instead of the dasbhoard info, we should be using this info instead.
http://www.azwater.gov/querycenter/query.aspx?qrysessionid=8CF17C8B1CB88E14E0534C64850A39FA

**Comment by rwjam** [comment]
Complete.
