### ISSUE TITLE
Kansas Municipal Water boundaries

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#114]
Lauren Paterson at Duke shared this:

https://services.kansasgis.org/arcgis15/rest/services/admin_boundaries/KS_RuralWaterDistricts/MapServer
_Says rural water districts but they had municipal too_

I'll look more if they have time-series data that goes with this

**Comment by rwjam** [comment]
(08/23/2022) Some county and Rural Water District boundaries, but no attached timeseries info.

![image](https://user-images.githubusercontent.com/17555073/186211320-e1cb6c7f-1c99-4a91-8c1b-81e83cafaf6b.png)

**Comment by rwjam** [comment]
Similar issue to this, will close for now: https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/issues/38
