### ISSUE TITLE
Review Minnesota water rights and water use data 

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#115]
Both Ryan and I attended this January 26, 2022 WUDR webinar: Cloud-based Water Conservation Reporting Tool for the State of Minnesota. Later this spring, I will reach out to the Minnesota to see if they'd be interested in sharing their data through WaDE. 

Mesonota water rights and water use data are publically accessible here
https://www.dnr.state.mn.us/waters/watermgmt_section/appropriations/wateruse.html

**GIS layer is an ESRI ArcGIS layer package (.lpk) file**
![image](https://user-images.githubusercontent.com/3268971/151242238-ab21d1c0-535d-4e8a-9300-87c73635f5bd.png)

**There is water source info.**
![image](https://user-images.githubusercontent.com/3268971/151242307-a3303220-2768-499f-bfb4-145114eccb9c.png)

**Ryan's initial evaluation as shared on Slack especially on this data: Water Use Data - 1988 to 2018  XLS**
https://files.dnr.state.mn.us/waters/watermgmt_section/appropriations/mpars_index_permits_installations.xlsx

- It would be nice if there was metadata attached to this....

- Looks like it's structured around the permits by the site.  So for example, there are duplicate entries for permit_number 1938-0007, with the same permit_total_volume_mgy, but to different sites (utm_x, utm_y).  Look's they 'may' track use per year in MG, but it's mostly blank...

- However, I do not see a way to attach this record info to the shapefile sites.  In the record data, I see no site name, no site native id, etc.  And in the shapefile, I see no permit number id, etc.

**Other info that might be relevant** 
https://www.dnr.state.mn.us/waters/watermgmt_section/appropriations/water-conservation-reporting-system.html

**Comment by amabdallah** [comment]
Let's make these changes

1. I see in the mapping document that **AllocationTypeCV** is set to be **permit_class**. That's the state allocation type, we also need to store the WaDE Name allocation type: Prior Appropriation.

2.  I see that **AllocationPriorityDate** is set to permit_effective_date. Let's leave AllocationPriorityDate blank because Minnesota doesn't follow prior appropriation. We may need to add a new field in the database for ~ effective date.

**Comment by rwjam** [comment]
As of 01/17/2024, we would like this MN data in uat, but NOT prod.
