### ISSUE TITLE
Error when importing new state data to WaDE QA DB

### ISSUE THREAD

**Issue by tsga** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#12]
The SQL db CVs.State is not automatically updating itself based on contents of the WaDE CV website. When attempting to upload date for a new state (e.g., WY) it causes a foreign key error.

**Comment by amabdallah** [comment]
Thanks for looking into it. So I think you need to run the ~”data flow” in Azure to force it. But it should update overnight otherwise. Or there is a deeper bug. I’ll look into it on Monday  

Adel Abdallah
