### ISSUE TITLE
ND Water Resource Districts

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#120]
Source link: https://www.swc.nd.gov/info_edu/water_links/water_resource_districts.html

(09/01/2022) Missing shapefile to work with.

"_Water Resource Districts (WRDs) are responsible for water management in North Dakota at the local county, or sub-county level. WRDs are typically comprised of three or more board members - addressing water management issues such as drainage, water control, watershed planning, and assessment projects. Water Resource Districts (WRDs) are also allowed to form joint districts by joining together to manage water and water projects across district boundaries_."

**Comment by amabdallah** [comment]
Jennifer Martin, Water Resource Engineer, Regulatory Division shared this through email

Attached are the shapefiles for the ND Water Resource Districts shown on the map below.

There are also existing joint water resource boards not shown on the map you linked. Additional information on joint boards and other water resource district information can be found on the [ndwater.org](http://ndwater.org/) website’s [ND Water Resource Districts Association page](https://ndwater.org/organizations/north-dakota-water-resource-districts-association/).

I’ll reiterate that this map does not include the joint boards, which can be found on the [ndwater.org](http://ndwater.org/) website link I previously sent you.


Unfortunately, the metadata is very limited and only provides basic geometry information. We plan to expand our database to include more information on water resources districts, but I don’t have a timeline on when that would become available.

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/bedff8e2-5ac3-4f15-9852-7e0f2d3045fc)

 

It may be worthwhile to contact the ND Water Resource Districts Association to check if they have any additional information. According to their [ndwater.org](http://ndwater.org/) page, they can be contacted at [staff@ndwater.net](mailto:staff@ndwater.net) or 701-223-4615.

**Comment by rwjam** [comment]
got data from email

joseph mapped this out.
