### ISSUE TITLE
WY - Evaluate/import import Reservoir and observation sites time series data

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#122]
See below notes.

**Comment by rwjam** [comment]
WY seems to have a Geospatial Hub too.  However, the data on there doesn't seem complete / missing elements.  Worth keeping an eye on as well.
- https://data.geospatialhub.org/

**Comment by rwjam** [comment]
New data option found by Adel

Guess what! Wyoming has this treasure

https://seoflow.wyo.gov/
I dont know if we can download all the sites and their metadata but I'm certain we can ask for a shapefile for them.

It seems they have an API for all the sites (site code) and parameters. Examples:

https://seoflow.wyo.gov/Data/List/Parameter/Discharge/Statistic/LATEST/Interval/Latest

https://seoflow.wyo.gov/Data/DataSet/Export/Location/06638090/DataSet/Discharge/Discharge.MDT/Interval/Latest

https://seoflow.wyo.gov/Export/DataSet?DataSet=Discharge.Discharge.MDT%4006638090&ExportFormat=csv&Compressed=true&RoundData=False&Unit=&Timezone=0&_=1670440496377

**Comment by amabdallah** [comment]
Adel reached out to Mel at the WY SEO, asking for the definition of "many discharge" parameters and the difference between them. Other than that, the data seems ready to be mapped and imported to WaDE
![image](https://user-images.githubusercontent.com/3268971/213560714-d0088148-885e-48f9-ad02-75d2479ea912.png)

**Comment by rwjam** [comment]
Note from Adel 01/23/2023.

> Let's also infer that site type=Reservoir/Lake.
> ![image](https://user-images.githubusercontent.com/17555073/214107317-02e60375-34b9-4d2e-9829-c49a8834382b.png)
