### ISSUE TITLE
New North Dakota (ND) water use data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#123]
Let's track this task here. Is it done? Could we have it added to the prototype here? or should we have a separate prototype? https://waterdataexchangewswc.shinyapps.io/SiteSpecific_Demo/

https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/tree/master/NorthDakota/SiteSpecificAmounts

https://drive.google.com/drive/folders/1DDuivrdXe58LlmN55RfH5h6HwWx6cqSQ?usp=sharing

**Comment by rwjam** [comment]
Let's do this but with the new pre-processing scripts so we can tie the sites directly to a water right record.

We would like to try and add NDwr water use timeseries to the ss demo too

**Comment by rwjam** [comment]
updated using new pre-processing scripts
https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/pull/309/commits/f79553784e2528bfbd75fbff537adfc64e3444a9
