### ISSUE TITLE
 "Cross group not valid" error at import of 'aggreagedamounts.csv'

### ISSUE THREAD

**Issue by tsga** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#13]
The import of the 'aggregatedamounts.csv' fails an error: "Cross group not valid". The full text of the error and the SQL procedure that causes the error are attached here.

This error is related to the data loader populating the metadata fields with zeros

[errText.txt](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/files/3990775/errText.txt)
[aggamountSQL.sql.txt](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/files/3990776/aggamountSQL.sql.txt)

**Comment by Rhipeus** [comment]
Can you please proved the data that you are trying to load?

**Comment by tsga** [comment]
Here is one for Wyoming aggregated data: 

https://drive.google.com/open?id=1PjUu08dDuVRQotlBIyxzIuRHASWi4gCd

**Comment by tsga** [comment]
Fixed. Tested with WA and ND data.
