### ISSUE TITLE
CO Water Rights Data

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#131]

**Comment by amabdallah** [comment]
@rwjam the next time you update Colorado's data (later), would you update their method table in your "processed data" CSV files? 
**Two updates** FYI I already made both changes to this [Google Sheet](https://docs.google.com/spreadsheets/d/1E0GTwwUa8_w0ZUBNKMZNxm-jBx9QlfrQjirXL-rvk30/edit?usp=sharing)
1. Remove the single quote in front of the method link URL
2. Add this additional disclaimer info (shared by an email) to the method description

I committed a data management sin by editing the table in the Prod database manually. I need to do that as I'm sending an email to Colorado so they take a look.

>  Important: to find out more about the water right in Colorado, the decree number would be the primary reference. "Priority Date" is not the terminology used in Colorado. Make sure to understand the Appropriation Date, Adjudication Date, and Priority Admin No. provided in Colorado’s water rights data. Colorado does not have a machine-readable water right owner name.


https://westdaat.westernstateswater.org/details/right/COwr_WR128224 


![image](https://user-images.githubusercontent.com/3268971/232111932-aea3bd40-3f30-4893-aa1a-742c3e9faf55.png)

**Comment by rwjam** [comment]
- removed the single quote from database / upload files.
- additional disclaimer info text was already in the method description
