### ISSUE TITLE
WY POU & POD mapping (bug?)

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#132]
I discovered what could be a bug in either the data mapping or the queries, at least for Wyoming. 

For the same water rights in the Green River in Wyoming, the POU sites seem to have a water source type as unspecified, while the PODs seem to have it as surface water. Based on our schema, POUs and PODs for the same water right relate to the same metadata and, thus same water source, right? Here are the two examples. Do you mind checking and see if the issue is from the original data,  data mapping, or WestDAAT?

POD water source type is surface water
https://westdaat.westernstateswater.org/?state=N4IgtghgDiBcoC8D2SwBkCmA3DAbOA7AHQCMBAnAKwUkkAcAbLQAwkAsANCLhAC4CWvAK4ATDHDYAmIgGY2DSs0kMCzKeUldcSAHYBzQaPGwAtCWblSZSmzYyGbZnQoBfLgHcATnFAAjDDoYAGb8AMb8ELgAqgDOGDFwANoAulxI7oGeAMI8MTH8IaF8-LoJsCkefBieAMpIQp6hGAAqAJ5Q8UkgNQ1BEE0ABADqVd6pIDG8VWUVIJ78OJ4AQhD5OgByEGCd5eP8OqG4RgCiAB4YYFC8cH24cVxQSCIACvVwIM8A8gAiIA9IuFauH2xlmOlwIn4ADF%2BLheNVvnwID5uMVhGIJMwiOQSJRKFpdAZ0cYzBYiGxKDJ8SBIZ4MKEBKU4CQuCIka99rwyiQXG4QODIQBBBkLYy8TxCDBcMBlCbijAYLkmLC0P78iH8FE8ATEzHY3HU7T6QwY0zmSwUqms-h0kVM2AsmnspCc7m8oA

POU.......water source type is unspecified 
https://westdaat.westernstateswater.org/?state=N4IgtghgDiBcoC8D2SwBkCmA3DAbOA7AHQCMBAnAKwUkkAcAbLQAwkAsANCLhAC4CWvAK4ATDHDYAmIgGY2DSs0kMCzKeUldcSAHYBzQaPGwAtCWblSZSmzYyGbZnQoBfLgHcATnFAAjDDoYAGb8AMb8ELgAqgDOGDFwANoAulxI7oGeAMI8MTH8IaF8-LoJsCkefBieAMpIQp6hGAAqAJ5Q8UkgNQ1BEE0ABADqVd6pIDG8VWUVIJ78OJ4AQhD5OgByEGCd5eP8OqG4RgCiAB4YYFC8cH24cVxQSCIACvVwIM8A8lEgD0i4rVw%2B2Msx0uBE-AAYvxcLxqgARPgQHzcYrCMQSZhEcgkSiULS6Azo4xmCxENiUGT4kAQzwYUICUpwEhcERI177XhlEguNwgMEQgCCDIWxl4niEGC4YDKE3FGAwXJMWFov354P4KJ4AmJmOxuOp2n0hgxpnMlgpVNZ-DpIqZsBZNPZSE53N5QA

**Comment by rwjam** [comment]
This issue would have been a result of the mapping we did for this data.  We have traditionally tied the water source type to the site immediately upon mapping.  For example, river withdrawal sites for PODs tend to also have associated water source type identifiers with them, while POU for say agriculture irrigation sites have historically not included what type of water is being used on that location.

You will find this similar issue among all data in WaDE throughout WestDAAT, as that is how we have mapped out the data up to this point.

Let set aside some time to talk about this issue as a whole together.
