### ISSUE TITLE
Import TX TCEQ reservoir data: Site Specific Reservoirs and Observation Sites

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#136]
Historic reservoir data for [Texas ](https://www.waterdatafortexas.org/reservoirs/statewide)is available for download here 
https://www.waterdatafortexas.org/reservoirs/download

This link gets all reservoirs' historical data, but I dont the reservoir code or name to associate it with its time series, right? (weird)
https://www.waterdatafortexas.org/reservoirs/statewide.csv

Another way is to loop through a list of their reservoir names and query their time series data one a time like this example:
https://www.waterdatafortexas.org/reservoirs/individual/b-a-steinhagen.csv

The reservoir names and their coordinates are available here:

> Statewide recent conditions are also available in CSV and plain JSON formats in the URLs below: http://www.waterdatafortexas.org/reservoirs/recent-conditions.csv **or** 
> http://www.waterdatafortexas.org/reservoirs/recent-conditions.json

![image](https://user-images.githubusercontent.com/3268971/207935473-5acfe9a8-8510-49e0-8102-8559d5de02a7.png)

**Comment by rwjam** [comment]
mapped and pushed to WaDE.
