### ISSUE TITLE
AZwr data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#14]
**Reading**
http://infoshare.azwater.gov/docushare/dsweb/Get/Document-11348/Groundwater_Code_Overview.pdf

**Data** I need to check with the AZ folks and ask for a bulk access
https://gisweb3.azwater.gov/igfr

**Arizona Department of Water Resources GIS Data**
http://gisdata-azwater.opendata.arcgis.com/

**WaDE 1.0 data** 
![image](https://user-images.githubusercontent.com/3268971/71381026-1a4c9900-258f-11ea-91bd-3905825290ff.png)

**Comment by tsga** [comment]
I used these files for groundwater wells from gis data (couldn't find any surface water related data):
       Well_Registry_Wells55.csv (data for all well locations, includes 'pumping rate' data)
       GWSI_Sites.csv (smaller file with detailed information about the location/site).
I joined the two tables with the common ID and imported the table to WaDE. The join reduces the total data rows to about 22544. We can revise this to just import data from the larger file "Well_Registry_Wells55" if we are OK with losing site information from the smaller table "GWSI_Sites".

**Comment by amabdallah** [comment]
We need to verify the range of priority dates in AZ with the AZDWR

**Comment by rwjam** [comment]
AZ data has been scrapped and removed from WaDE 2.0 for now.

This data is only related to Groundwater and well (no surface water).  In addition, AZ does not track priority date for most of it's known groundwater or wells (exception being those sites within an AMA).  In addition, after a meeting with AZ, there was a concern from AZ of the public misinterpreting  this shared information.  To be safe, we have removed the AZ water rights data for now.  

We are looking for surface water rights.

**Comment by amabdallah** [comment]
https://new.azwater.gov/news/articles/2022-03-08

**Comment by amabdallah** [comment]
Opening this issue to revisit this new app/updated data(?)

https://new.azwater.gov/news/articles/2022-03-08

**Comment by rwjam** [comment]
Looks like  new interactive app ([link](https://experience.arcgis.com/experience/dccd34942e394028860e7505bd52fc8a/)) is in it's prototype phase.  There is also **no download option** for this app.

**Comment by amabdallah** [comment]
@rwjam any idea why the "bushman" owner's name is not showing up in WestDAAT owners? 
Per this other [GitHub issue in WestDAAT ](https://github.com/WSWCWaterDataExchange/WestDAAT/issues/200), Michelle found her grandpa's water right in Arizona through this search http://www.azwater.gov/querycenter/query.aspx?qrysessionid=ABBBE0BF2A69326CE040000A16005CA1

I see in your [mappings](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/tree/master/Arizona/WaterAllocation#6-code-file-6_az_allocationsamounts_factspy), that AllocationOwner for surface water is mapped from HLDRNAME. 
Do you mind checking there and seeing what is happening?


When you look into other Data Table part of the Analytics section in WestDAAT, there are no rights for the Bushman owner name in Arizona 

https://westdaat.westernstateswater.org/?state=N4Ig7gTiBcoIYBsEHsDGcAuBLZA7A8mLgKZTQgBGArgM4AWAtnLiADQgAOyCAngliRgBtALrtcCACZYAYlgQZSAEUxwYoBJiwYqk4jFxUk7FLgDm23fuiHjIaRGKpseGjADM7SaoAKyARhu0ADsAL6h7Ewc6iAAXsjIDAAyxABuxAgwAKwAdABsACxFABxZ7nlZAJwATMUADAWVJlo6eh7uOQCM9VnVBVl5nQXujcUmeBat1gC0nXWVOWWdle6dIwXVlVnBxeFAA

**Comment by amabdallah** [comment]
Lisa Williams shared this new dataset. Let's evaluate it 

https://drive.google.com/drive/folders/1XX7DKY663FhUpbxAPPW_UgWtBcaoeeNC?usp=share_link

**Comment by amabdallah** [comment]
@Ryan found these issues: 

1. There is a mismatch between the water right identifier in the shapefile and the query system.
SW Query System: 33-11.0
Fillings shp file: [33-000011.0000](tel:330000110000)

2. The Query system here has not-so-common units that are not defined. We need to understand them as we convert all flow values to CFS and Volume to AF
https://www.azwater.gov/querycenter/query.aspx?qrysessionid=ABBBE0BF2A68326CE040000A16005CA1
![image](https://user-images.githubusercontent.com/3268971/222287390-b9603824-51f9-471d-9725-4be2fde91699.png)

**Comment by amabdallah** [comment]
@rwjam is staging maptiler up to date with the UAT database? WestDAAT is not showing any GW rights in AZ but the Analytics (from the backend database) does have a lot.

https://westdaatstaging.westernstateswater.org/?state=N4IgtghgDiBcoC8D2SwBkCmA3DAbOAHAHQDMA7CeQQCxkCMZAbHSQJx0A0IuEALgJa8ArgBMMcEtSLVWZdjOYAmAAz06AVi64kAOwDmg0eNgBaOudIL1jRoraNlBOgF8uAdwBOIuKChJ%2BOrwAyvwIxiAAZiBckFAA4h5IQlABenAgAEZCIK4gnj6ZGDoYEfwAxvwQuACqAM4YtXAA2gC6XEhuxR4Awjy1tfylZXz8uo2wre58GB5BSR5lGAAqAJ5QDc0gCUk6Im7THiBtILW80%2BNNIACCAFpHXB78OB4AQhADOgByEGAbE8cBMq4IwAUQAHhgwFBeHAIlV6lw-LgVrgAsZJiAdLgRPwAGL8XC8GYAET4EDgOiEuFwzmcQA
![image](https://user-images.githubusercontent.com/3268971/230469298-9977bd8a-0051-4fb8-9062-013fbe546bc1.png)

**Comment by rwjam** [comment]
Interesting bug catch (see below).

As per a previous conversation we determined that AZwr for groundwater records do not come with a priority date.  We decided to go back and make them 'Exempt' to better match the provided state data (we were originally using a filler date as a temp solution).  Groundwater water rights in AZ can be seen if you use the Site Content toggle buttons.

There is a bug here this issue highlights.  The Chart Summary & Data Table tabs are not responding to the Site Content toggle buttons.

![image](https://user-images.githubusercontent.com/17555073/230634175-4d45c693-7edd-4b1a-8bf6-6bcd3330304b.png)

**Comment by amabdallah** [comment]
Paul Alder, Water Resource Manager, Surface Water, Statewide Planning and Permitting at AZ DWR said:

> Arizona's standard for surface water is what the majority of California uses. 1 Miner's Inch = 40 CFS (cubic feet per second) .....1 Miner's inch = 11.22 GPM (Gallons per minute) or 18.091 AFA (Acre feet Annum or Annually).

**Ryan asked del**

> Interesting.  Do you have an understanding of how these conversions are working?  Looking through them, they seem to not agree with one another.
> 
> 1 Miner's Inch = 40 CFS
> 1 Miner's inch = 11.22 GPM or 18.091 AFA
> 11.22 GPM = 18.091 AFA (this seems correct)
> However 40 CFS is not 11.22 GPM, it should be 17954.4 GPM.
> 
> 1 Miner's Inch = 14.49 Acres at 1 foot
> 1 Miner's Inch = 18.11 Acres at 9 inches

**Adel's response**
Regarding AZ Miner's inch unit conversion. Could you update this table with a new column to include the count of rights that each unit has? to inform us of how big this issue is.
So we need to convert the miner inch into either Volume or Flow. Miners Inches per Annum is volume per year. So that goes into AF/Year.
Let's get a sense of the count of these units and I'll email AZ back

**Comment by rwjam** [comment]
Lack of metadata or comparable state landing page makes this data hard to interpret.  Seems like they don't provide anything related to a SiteNativeID to work with.  Caught some bugs in WaDE where POUs shared the same SiteNativeID as PODs.

As temp fix will have to create our own unique SiteNativeID for AZWr to prevent this error until AZ can provide us with this information/

**Comment by amabdallah** [comment]
I came across this unit conversion sheet for Idaho and noticed 1 Miner’s inch=0.02 CFS or 9 GPM, so I thought to share it here.  It seems Miner's Inch value is not universal 
https://idwr.idaho.gov/wp-content/uploads/sites/2/water-measurement/Water-Conversion-Factors.pdf
