### ISSUE TITLE
Convert Owner name "all caps" into Capital first letter only in each word

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#146]
**Problem**
All caps can be hard to read and they look odd to me especially if the rest of the metadata is different. See the screenshot below.

**Suggested Solution**

Ideally, we want to capitalize just the first letter of each word "name" in an owner's name. 
https://learnpython.com/blog/uppercase-letter-python/

![image](https://user-images.githubusercontent.com/3268971/232160225-a0cae3d7-04ed-40f4-ab4a-eecb4a5f4658.png)

**Comment by rwjam** [comment]
I should be able to go back and make sure all owner names are in title() format during the preprocessing.

**Comment by amabdallah** [comment]
I think this is done, right? if so, feel free to close the issue

**Comment by rwjam** [comment]
There might be a few hold outs, but with every update to the states data this will be included.
