### ISSUE TITLE
Update Flow and Volume mapping: North Dakota (ND) Water rights 

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#147]
**Problem**
So we need to update the input flow and CFS columns in this dataset to be for the "Approved" values instead of the "Required" values. This is a super interesting case where North Dakota shares both the application required values along with the approved ones. We care about the approved ones 

**Solution**
1. Not too bad, let's just switch the input columns to the ones in red (see screenshot below)
2. Let's also add this text part of their Method description 

> The Approved Acre-Feet, Acres, Rate, and Storage listed for the Permit may differ from the combined totals presented with the Points of Diversion. The totals that are presented with the Point of Diversion represent the maximum that can be withdrawn at that point. However, the withdrawals from all of the Points of Diversion are still not to exceed the totals allocated for the Permit.

**ReadME** location to be updated
https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/tree/master/NorthDakota/WaterAllocation#operation-and-steps-6

### Here is an example that helped me compare and understand the difference: thanks a lot for adding the native webpage. 
**State URL**
https://www.swc.nd.gov/info_edu/map_data_resources/waterpermits/single.php?id=751

**WestDAAT URL**
https://westdaat.westernstateswater.org/details/right/NDwr_WR8141

![image](https://user-images.githubusercontent.com/3268971/232346463-27d3b203-1843-4fe1-93a7-d2b49ccb0746.png)

**Comment by rwjam** [comment]
Changed CFS and AF inputs to use the appropriate fields.
Added Irrigated Acres.
Updated method description.
