### ISSUE TITLE
Update Nebraska (NE) Native Water Allocation URL Structure

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#149]
**Problem**
Most (all?) NE native URLs are not working for me. 
**Example**
https://westdaatstaging.westernstateswater.org/details/right/NEwr_WR284
**Diagnoses**
I looked at the original landing page structure in NE and the difference is that they don't have **ForPublic** in the URL. If you remove that part, the links work fine. NE probably changed this recently.

**Docs to be updated as well**
https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/tree/master/Nebraska/WaterAllocation#6-code-file-6_newr_allocationsamounts_factspy

![image](https://user-images.githubusercontent.com/3268971/232516107-a832862d-328c-470e-a00d-ec451b5cb2ba.png)

**Comment by rwjam** [comment]
Removed the **ForPublic** portion from the url.
