### ISSUE TITLE
Idaho water right: why values are zeros for this one?

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#154]
@rwjam any idea why the permitted flow or volume of this water right has zero values? the state native page shows values and this is a huge water, right? Is it a data source issue? This is a Reclamation contractor

https://westdaat.westernstateswater.org/details/right/IDwr_WR63136_1?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YBGABgDoOB2DgGwCAHLwAsvfPg4AmAbxKokWAK4ATZDDEBmLgFYBMmW3wC9%2BbRbZ7FNAHYBzVRpjY2bAfpm9D24QO0BMQ5tbQBfMKA

**Comment by amabdallah** [comment]
Oh well, there is a larger issue here that probably has to do with many*to*many relationships 

https://westdaat.westernstateswater.org/?state=N4Ig7gTiBcoA4HsA2BPJBLAdgUxgbQF0AaETJAE3QDF0kAXbCAEQEM6WZQk306BXcrmiY%2BSJCSQJMAc14ChIsSUoRsAYzropAZxgBmZWxYAFBFjq7oAdgC%2BJFmIRqeUgPJgcUaCABCZ7dgABMYQCABW6nSBfiwQ5IEIAGaBAMJSdKFIIHYgALYscJwgAF4ICLkAMtgAbthZ0AAcAHQAnC0NAEx6HQ1WVgBsAIydLQAsEjz8gjCjek39o1aDHStWDbP9XRJSslNCALSDg-1NeoN6VgAMAKxt11azKzY2QA


![image](https://user-images.githubusercontent.com/3268971/234701401-bd4a7ea1-47d6-4976-a5e6-a67c4790669a.png)

**Comment by rwjam** [comment]
Update pre-processing and wade input file creation to prevent accidental duplicate records from being entered in like this.  Have applied the changes to IDwr and pushed to stagging.

https://westdaatstaging.westernstateswater.org/?state=N4Ig7gTiBcoA4HsA2BPJBLAdgUxgbQF0AaETJAE3QDF0kAXbCAEQEM6WZQk306BXcrmiY%2BSJCSQJMAc14ChIsSUoRsAYzropAZxgBmZWxYAFBFjq7oAdgC%2BJFmIRqeUgPJgcUaCABCZ7dgABMYQCABW6nSBfiwQ5IEIAGaBAMJSdKFIIHYgALYscJwgAF4ICLkAMtgAbthZ0ACcAHQADABsei0AjA1WegBM-W0AHA0SPPyCMAAsek0ArP16813TXV0rw-0twxJSspNCALTrbU1DI1ZW8w0NPV3D0zY2QA

**Comment by amabdallah** [comment]
Looks great to me; thanks for the updates.
