### ISSUE TITLE
Idaho and Montana water right owner classification: Revise?

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#155]
Idaho and Montana water rights owner classifications appear to have some issues. I remember that Idaho truncated the rest of the owner's name, and they provided a separate dataset to get the full owner name. The classification code might need revision to make it smarter. For example, if the United States of America is mentioned along with the Forest Service, the owner should be classified as Forest Service. I'm unsure if the code already does that, but that is what comes to mind. 

https://westdaat.westernstateswater.org/?state=N4IgtghgDiBcoC8D2SwBkCmA3DAbOAbAHQCMADAEwAcAnAOwAsZDAzBeWSwDQi4QAuAS34BXACYY4DBkQIMqbZjRZkqAVhIUeuJADsA5sPGTYAWhLkiamlRI0K9lrYYkGAXx4B3AE5i4oKCRBXX4AZUEEExA-HkgoAHFvJBEoYP04ECQAYT4AZ1yQDxAffxAAIwxdDAAzQQBjQQhcAFVcjALYAG0AXR4kTyrvHIh8wVq6gUE9Ds6QZt1hDDEAAlD%2BAXblpGrlgEEwDG96iBBe4o3vUOTvOowAFQBPKHa4Hp5c9f4XrrOjnG8AEIjYIAOQgBxmZ2CdVwxgAogAPDBgKD8ODVJptHiBXAPXDBExvEC6XBiQQAMUEuC%2B3gAIgITrBdCJcLg3G4gA

### Example
**Problem**: classified as "United States of America."
**Solution**: should be classified as Forest Service
https://westdaat.westernstateswater.org/details/right/MTwr_WR41D%2053870%2000?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YBGNgOgHYBWADm4AGAGz5RfEQGZeAFhKokWAK4ATZDFm9OI7rKn5hQmfxEiATApoA7AOYr1MbB3Od%2BU2UPwjj-fP8MAX0CgA

![image](https://user-images.githubusercontent.com/3268971/235181695-e296d4fa-ddc8-4524-af05-10c48b7ce0d2.png)

**Comment by rwjam** [comment]
- Updated Forest Service and Wildlife classifications to include more generic terms.
- Reordered classification search to have United States be more generic-> search for more specific entries.
- Included a "Private" classification at the end to catch cases that use a similar USA title in their, but are LLC, INC, CORPs, etc.
- Updated MTwr, IDwr, and WYwr to reflect these changes.

**Comment by amabdallah** [comment]
The problem seems to persist in Idaho. The owner name appears to be truncated 

**Prod**
https://westdaat.westernstateswater.org/details/right/IDwr_WR6325052?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YBGAZgDoA2fABgCsHACwAmDgHYRMwfg4lUSLAFcAJshgjuknsIAckyRLH8xbfD0U0AdgHNVGmNjZsRXfPv3bJ%2BnhfxAngBfYKA

**Staging**
https://westdaatstaging.westernstateswater.org/details/right/IDwr_WR6325052?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YBGAZgDoA2AdgAsABjYAOfGx4SArD2l8SqJFgCuAE2QwB3PnI6i%2BfAEwcjQo23w9FNAHYBzVRpjY2bAV3yjR2vqJ6W%2BEE8AL4hQA

**Comment by rwjam** [comment]
Correct, we don't have that extra ID data anymore.

**Comment by amabdallah** [comment]
Thanks for making the changes and updates. Looks good to me
