### ISSUE TITLE
Odd POU for a WAwr.

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#159]
This is an odd POU for this wr in WA.  It is essentially the entire river.  The native page doesn't show this.   I suspect this might be due to an odd shapefile the state shared with us.

WaDE Prod: https://westdaat.westernstateswater.org/details/right/WAwr_WR2045734?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YB2AOjYBYBWAJl7cAzCIAMYgIz8AbDJKokWAK4ATZDG4yO3XbrH5uADl4zJk3gpoA7AOYr1MbNLEchU-DPy8D-bwF9-IA

State native landing page: https://appswr.ecology.wa.gov/waterrighttrackingsystem/WaterRights/WaterRightRecord.aspx?waRecId=2045734#no-back-button

**Comment by amabdallah** [comment]
This is a groundwater well-based water right, so something is wrong; either the original data as you pointed out or some sort of data join went wrong. 

When I looked at the pop-up card on the WestDAAT landing page (see screenshot), the water right native ID does not match. Is that correct?  
![image](https://user-images.githubusercontent.com/3268971/236895877-d242ef72-da0d-40fc-8087-bd78b5a84297.png)

**Comment by rwjam** [comment]
new join approach for POU info and POU geometry.  The POU to POD relationship for that particular site seems to have been resloved [westdaat link](https://westdaatstaging.westernstateswater.org/details/right/WAwr_WR2279898?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YBGADhNSSwFcAJshgAWDgDoArG0kBmfJw4A2AAxsRAJgDs3GgDsA5vyExsbDRvFb8HDUqWzVsrVrZaAvu6A).

As a whole, it's hard to get a good picture of what WA POU info is like.  They do so some POU info on their native landing pages, but it doesn't seem to connect very well to PODs / you have to zoom in close on the map for that POU layer to appear.
![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/17555073/a21ddbde-04d0-4e4d-b992-1d27c28f962d)

**Comment by amabdallah** [comment]
Nice work. I've tested many water rights, and they all seem to make sense.
