### ISSUE TITLE
Import Regulatory overlays for Idaho

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#164]
Let's import those three groundwater regulatory overlays for Idaho.

1. Rathdrum Comprehensive Aquifer Management Plan
https://data-idwr.hub.arcgis.com/datasets/rathdrum-comprehensive-aquifer-management-plan/explore?location=47.659020%2C-116.087083%2C7.73

2. Treasure Valley Comprehensive Aquifer Management Plan
https://data-idwr.hub.arcgis.com/datasets/IDWR::treasure-valley-comprehensive-aquifer-management-plan/explore?location=43.145589%2C-115.877224%2C7.65

3. Eastern Snake Comprehensive Aquifer Management Plan
https://data-idwr.hub.arcgis.com/datasets/eastern-snake-comprehensive-aquifer-management-plan/explore?location=43.381268%2C-114.298158%2C6.03

**Comment by rwjam** [comment]
These are essentially just named areas / polygons.  Is there any info related to the regulatory overlay information that would be tied to those polygons.  Something that lists out the rules important to these areas?  Need at minimum a link to some kind of web document, website, etc.

Are these groundwater, or surface water regulatory overlay information?

**Comment by rwjam** [comment]
something like these I guess?

- Eastern Snake River Plain Aquifer CAMP: https://idwr.idaho.gov/iwrb/water-planning/camps/espa/

**Comment by amabdallah** [comment]
Exactly, these work as URLs for each of the regulatory overlays. 
In essence, we want to capture high-level metadata to allow data query and filtering with a direct URL to each regulatory overlay.
