### ISSUE TITLE
Minting WestDAAT UUIDs: removing spaces or adding underscore?

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#167]
**Problem** 
Having spaces in UUDs may cause a problem when a user (e.g., Reclamation) tries to generate a URL for the landing page based on the UUID they get from our data download or API. 

**Example**
WaDE Water Right Identifier
WYwr_WRCR CC62371

In this example in Wyoming, our landing page adds % to fill the spaces in the UUID. 
https://westdaat.westernstateswater.org/details/right/WYwr_WRCR%20CC62371

**Solution** 
1. Leave as-is
2. Removing spaces
3. Replace spaces with underscore

**Challenge** 
We're trying to be consistent by generating a UUID based on the exact state identifier and not messing with the pattern of minting UUIDs.

**Comment by rwjam** [comment]
I think that is reasonable and we should be able to accommodate easily enough.  We will probably plan on removing all unnecessary spaces and special characters used to define a native water right id.

- NMwr example: https://westdaatstaging.westernstateswater.org/details/right/NMwr_WRUP00047?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAXyA
