### ISSUE TITLE
Montana (MT) Update "Applicable Resource Type" Surface Ground Water

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#169]
Let's update  the "Applicable Resource Type" Surface Ground Water to  Surface Water and Groundwater
https://westdaat.westernstateswater.org/details/right/MTwr_WR40H12453900

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/cf0ae912-e175-4e62-a93a-4434f9a10705)

**Comment by rwjam** [comment]
This changed has been made.
