### ISSUE TITLE
Map and import North Dakota water rights data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#18]
**ND State Water Commission MapService**

https://mapservice.swc.nd.gov/

Click at the top left corner "Tutorial" which will download a 5 min video that explains the map service

**Download the water permits datasets into a shapefile**

![image](https://user-images.githubusercontent.com/3268971/71585941-8d956400-2ad5-11ea-8070-aa7d6eb75bb4.png)

Check permit metadata and reported water use
![image](https://user-images.githubusercontent.com/3268971/71586229-b538fc00-2ad6-11ea-8c2e-26e4de31218b.png)

**Comment by tsga** [comment]
Data imported successfully (No "cross group validation" error happens here).

The following still need resolving, but they are part of other issues so am closing this issue.

1.  "LegalStatusCV" terms were manually entered in SQL Server MS .
2. CV.State is not still being updated by the "AutoUpdateCVData" trigger

**Comment by amabdallah** [comment]
Let's reference this issue in the ReadME file that describes how we got the data
Also, let's add the downloaded shapefile (as-is) to the input folder

**Comment by amabdallah** [comment]
Hi @rwjam 
Did you download this shapefile after Teseganeh back in 2020? It's worth downloading it again and pulling any updates. 
More importantly, the map service here displays POUs. I'm wondering if what we have in the database right now is the centroid of those POUs. The ReadME mentiones the use of long. and lat. which is unclear to me where those came from.

 As we now accommodate POUs geometry in the database and WestDAAT, would you please revisit this data and see if these are just POUs? it would look great in WestDAAT to have them up there.

**Comment by rwjam** [comment]
Download to shapefile is that little green button, if available.
![image](https://user-images.githubusercontent.com/17555073/166798421-c71acc85-c3b1-4ce9-b70d-90808206c431.png)

**Comment by rwjam** [comment]
Following up on this.  

- Looks like Teseganeh originally downloaded it -> exported and provided us with a csv file.  Within the file there are lat and long values to work with.  Not sure if those are meant to be the centroid.  Looks like we can download it again at anytime.
- Looking through the data I believe this is representational POD provided in a polygon shape.  So each of those squares is POD.  I'm not sure if any of this is POU information.

**Comment by amabdallah** [comment]
**Update URLs and organization name and contact info**
1. Let's update the agency's name to [North Dakota Department of Water Resources](https://www.dwr.nd.gov/reg_approp/waterpermits/). They no longer have the Commission as they merged agencies. So let's also update the abbreviation to something like ND-DWR. We need to update our database's agency/data URL to http://dwr.nd.gov/reg_approp/waterpermits/. The old link is broken now.
2. Let's update the contact person to be 
Chris Colby
North Dakota Department of Water Resources
ccolby@nd.gov

**Comment by amabdallah** [comment]
1. Let's update the Maximum Amount Unit to AF, right?
2. Let's revisit the "statistic" value for all the states. I think this should be "instantaneous., meaning they can pump water at this rate. 
3. This is a general comment; perhaps we should hide the entire variable card. I see it being confusing for water rights data. 
https://westdaatqa.westernstateswater.org/details/right/NDwr_WR8478?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YBGABhNSSwFcAJshgAWABwA6AEwB2GQFZ5%2BZSuUA2NdxoA7AOb8hMbJw4SR%2BAMxr5AXxtA
![image](https://user-images.githubusercontent.com/3268971/183991974-35d5baf7-dc24-40e1-b060-3d6dd7600357.png)
