### ISSUE TITLE
Capitalize USA or LLC in the owner name 

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#181]
Owner names need a bit more complex handling to look more professional in WestDAAT. Two examples I came across are USA and LLC. 

USA
https://westdaatstaging.westernstateswater.org/details/right/UTwr_WR911105

LLC
https://westdaatstaging.westernstateswater.org/details/right/AZwr_WR200049

Another example is BIA
https://westdaat.westernstateswater.org/details/right/IDwr_WR5513487

**Comment by rwjam** [comment]
I'll see what can be done.  These are little python things to make edits too.

Unfortunately, is really depends on how the state is sharing that info.  In both of these cases the source data provided those owner names all in capital letters.  It was a data processing format decision I made to ensure that all names followed a .title() format.  That way everything going into WaDE was consistent across all data inputs  (e.g. "GEORGE FAMILY LLC" became "George Family Llc", "ON BEHALF OF SHOSHONEPAIUTE ACTING THROUGH BIA" became "On Behalf Of Shoshonepaiute Acting Through Bia").

I'll see if I can add a few additional scripts to ensure that all abbreviated names stay capitalized (.e.g, Llc = LLC, Usa = USA, etc etc).
