### ISSUE TITLE
New Oklahoma (OK) site-specific RO time series data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#182]
**New portal for Oklahoma using Aquarius (similar to Wyoming)**
https://data-owrb.aquaticinformatics.net/Content/Manuals/en/UserGuide.pdf

**Portal**
https://data-owrb.aquaticinformatics.net/Data

**Comment by rwjam** [comment]
Having trouble downloading all the site info / wanted time series info.  Having to do one file at a time, which is turning into too much stitching.  According to the user guide, there should be a way to bulk download multiple files / datasets, but this feature ‘might’ be hidden behind login credentials.  

Adel to help with reaching out to OK and possibly setting up a WSWC account and see if that does the trick.

**Comment by rwjam** [comment]
To meet our upcoming deliverable, ;let's just grab what we can for now.

- Let's get Select parameter = Discharge (roughly 14 sites, but those 14 may not have mean daily...).
- Download Select Value = Longitude, Latitude, Location Identifier (at least 3 different downloads, will need stitching).
- Download timeseries Discharge.Mean.Daily (if they have it) timeseries info with a 'Entire Period of Record' date range, will need to stich.

The download timeseries doesn't provide a itendifer to stich too, we 'might' be able to use the api link to mannualy add this in via an api all.

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/17555073/85217d95-8ef9-40b7-b79c-489a224cf2f1)

**Comment by amabdallah** [comment]
FYI Justin emailed me saying they added the "download button" now on the left side bar. 
I noticed that their API supports selecting multiple sites at the same time, so you could add 7 datasets and use the API URL for one call for all of them at once. 

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/7cdac3e5-f51c-48dd-8db5-b222042afa58)

**Comment by amabdallah** [comment]
Update form Justin 

_Wanted to give you another quick update. We have API access enabled now, so a data export URL will be available via the Export tab._

**Example**
https://data-owrb.aquaticinformatics.net/Export/DataSet?DataSet=Discharge.Mean%20Daily%40FSPO2&Calendar=CALENDARYEAR&DateRange=EntirePeriodOfRecord&UnitID=119&Conversion=Aggregate&IntervalPoints=Daily&ApprovalLevels=True&Qualifiers=undefined&Step=1&ExportFormat=csv&Compressed=true&RoundData=False&GradeCodes=False&InterpolationTypes=False&Timezone=-6&_=1693251294966

**Comment by rwjam** [comment]
That should work.  Do this as string:

_"https://data-owrb.aquaticinformatics.net/Export/BulkExport?DateRange=EntirePeriodOfRecord&TimeZone=-6&Calendar=CALENDARYEAR&Interval=PointsAsRecorded&Step=1&ExportFormat=csv&TimeAligned=True&RoundData=False&IncludeGradeCodes=False&IncludeApprovalLevels=True&IncludeQualifiers=undefined&IncludeInterpolationTypes=False&Datasets[0].DatasetName=Discharge.Mean%20Daily%40"_  + **LocationIdentifier** from the stitch of site information

**Comment by rwjam** [comment]
pushed https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/commit/0f5d6f075b72755e92d8bab94a513443ad909998
