### ISSUE TITLE
UT regulatory Great Salt Lake Basin

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#187]
let's include a shared shp file as the Great Salt Lake Basin as a regulatory area to add to water rights.

input file will be saved in UTre inputs (GreatSaltLakeBasin.zip)

water source type = surface water

file source = email from Laura Vernon, the Great Salt Lake Coordinator with the Utah Department of Natural Resources Division of Forestry, Fire and State Lands (lauravernon@utah.gov)

https://drive.google.com/file/d/1zXU8abs7vxj-GMqRx-uO9A-WhiuSkXmn/view?usp=drive_link

**Comment by rwjam** [comment]
mapped & loaded to WaDE

**Comment by amabdallah** [comment]
Here is a better polygon to use, which only applies to the Utah portion (scope of regulation)
Shared by email on 12/07/2023, from Jim Reese at Utah DWRi
[BasinsClosedToNewAppropriations.zip](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/files/13602812/BasinsClosedToNewAppropriations.zip)

**Comment by rwjam** [comment]
Let's combine these with https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/issues/279
