### ISSUE TITLE
Import South Dakota Water rights

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#19]
https://denr.sd.gov/des/wr/wrprimer.pdf

**Comment by tsga** [comment]
Here is a link to data downloaded from the website. This doesn't have site (POD) location coordinates (latitude and longitude). Need to get these information in order to be able to import the data to WaDE. Alternatively, the site information in the column "Legal Description:" (in the form of NE/SW/NW/SE....) has to be converted to coordinates.

https://drive.google.com/open?id=16TxQ0ekkEGVZLkUwIbNXGCFbkiuqmKeN

**Comment by amabdallah** [comment]
@tsga let's chat about it on Friday. Not sure what is there in the NE/SW/NW/SE values but I'm wondering if we could convert them to long and lat. But I'll have to check with those folks and see if they can add long and lat for us. 
Sometimes, states avoid adding direct long and lat for access security reasons

**Comment by amabdallah** [comment]
Okay! So here is the table that downloads as XML. It would be ideal if they make it download as CSV. 
 https://denr.sd.gov/des/wr/dbwr.aspx

So the question is if we can programmatically this value into a long and lat: SW1/4NW1/4 Sec. 4 T21N-R2E. I doubt it! this could be very tricky and needs checks and validations. We'll definitely refer to the SD folks on this. 
 
Permit location.
https://denr.sd.gov/wrimage/wrinfo/wr_div1/1624-1.pdf


![image](https://user-images.githubusercontent.com/3268971/73077517-8ae02180-3e7d-11ea-940b-d7c5d4f36361.png)

**Comment by amabdallah** [comment]
Ron Duvall shared a map package of this map with us. We'll import the data from that package
https://sdbit.maps.arcgis.com/apps/Embed/index.html?webmap=0b1628de815e4047b717a7ed18779b94&extent=-108.6057,40.0488,-92.3789,47.758&home=true&zoom=true&scale=true&details=true&legend=true&active_panel=legend&basemap_gallery=true&disable_scroll=false&theme=light


![image](https://user-images.githubusercontent.com/3268971/100122919-3740ba80-2e37-11eb-95ae-57907efc335b.png)

**Comment by amabdallah** [comment]
See this here too

https://denr.sd.gov/des/wr/dbwrsearch.aspx#textsearch

**Comment by rwjam** [comment]
Map package received from Ron Duvall from personal correspondences (email).  South Dakota currently does not share water right info in an easily downloadable format / shapefile.

**Comment by rwjam** [comment]
Data mapped and uploaded to QA.
