### ISSUE TITLE
Revisions needed to old codes (and data if re-importing to WaDE2 DB)

### ISSUE THREAD

**Issue by tsga** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#20]
This is a list of revisions required so that the old codes that generated inputs to WaDE DB (e.g., for CO state) can be fully compatible with the recent changes made to the DB tables by DPL. The data have already been imported to WaDE and the modification are only required if there is a chance/need to re-import them. 

I think these changes are low priority items but I am putting them here to make sure we remember them and get back to them "when we have time".

These apply to the states UT, CO, OK, MT, NM, TX, WA ( and possibly WY. The input for WY includes 'PowerType' column but not sure if the Python code also was modified). 

And let's update this list as we find more related issues.

1. Add "PowerType" and "GeneratedPowerCapacityMW" columns to water allocations table.
2. Remove "GeneratedPowerGWh" column from water allocations table.
3. Add "AllocationTimeframeStart" and "AllocationTimeframeEnd" instead of "TimeframeStart" and "TimeframeEnd", respectively, in water allocations table. 
4. Add "PowerType" to aggregatedamounts.csv
5. Change "WaDESiteUUID" to "SiteUUID" in "sites.csv"
6. Add "StateCV" to "sites.csv"

**Comment by amabdallah** [comment]
@tsga thanks for creating this issue. How about WaDESiteID? and changing it to NativeSiteID?

Could you list all the states (old) that need this update?

**Comment by amabdallah** [comment]
@tsga there are two more. The site table should have "SiteNativeURL" See here: https://schema.westernstateswater.org/tables/Core_Sites_dim.html

and the allocation table should have WaterAllcationNativeURL
see here
https://schema.westernstateswater.org/tables/Core_AllocationAmounts_fact.html

**Comment by tsga** [comment]
OK I added "SiteNativeURL". All the states (CO and UT included) already have allocation table with "WaterAllcationNativeURL"
