### ISSUE TITLE
TCEQ surface water rights

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#204]
**Problem**
The Water Source Type for all TCEQ surface water rights is set to "blank."

**Suggested solution**
All TCEQ water rights are for surface water. 

# Staging
https://westdaatstaging.westernstateswater.org/?state=N4Ig7gTiBcoM4BcCGCCmcYG0QBUAaIAugDQgCWcAcgDYAmZAYmdWhAIIDGCZAbqjADMk1OKgC%2BpSLRigADgHsyAOwQBlMgC9%2B0ENNIBbJLIDiEeQFdZygOYxwcHAE9Z-CSEOyZIDfPn6AMqh81DAArAB0AJwAHACMoQAsCQDMydHRAAwA7LFJoaTUKGQI5rTayQBM4RnROfkg1PJK1sWl2gC0MeEAbMnd8WJiQA
![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/c283273d-dc02-4fce-a6e8-6e142305f565)

# Prod

https://westdaat.westernstateswater.org/?state=N4Ig7gTiBcoM4BcCGCCmcYG0QBUAaIAugDQgCWcAcgDYAmZAYmdWhAIIDGCZAbqjADMk1OKgC%2BpSLRigADgHsyAOwQBlMgC9%2B0ENNIBbJLIDiEeQFdZygOYxwcHAE9Z-CSEOyZIDfPn6AMqh81DAArAB0AJwAHACMoQAsCQDMydHRAAwA7LFJoaTUKGQI5rTayQBM4RnROfkg1PJK1sWl2gC0MeEAbMnd8WJiQA

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/8979c774-8c96-47ea-9165-bfed8759a7df)

**Comment by rwjam** [comment]
Updated stagging / stagging maptiler.  All TCEQ rights are now surface water.  All TWDB are now groundwater.
