### ISSUE TITLE
WaterAllocationTable doesn't conform to the table type of the parameter

### ISSUE THREAD

**Issue by tsga** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#21]
While attempting to import water allocations table, the following error occurs when SiteUUID has longer strings (because a row in water allocations table can have multiple Site IDs):

String or binary data would be truncated.\r\nThe data for table-valued parameter \"@WaterAllocationTable\" doesn't conform to the table type of the parameter....

Solution: the length of the siteID was bigger than upper limit in the DB; For now drop rows with longer SiteID values than 250 characters

**Comment by amabdallah** [comment]
@tsga Could you add a couple of those long sites here as examples? We could push it to 500 char but want to know if that would be enough

**Comment by tsga** [comment]
Here is an example for Oregon (Github and Google, same file).
500 covers most string lengths, but there are times when 500 was exceeded (but few).

https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/blob/master/Oregon/WaterAllocation/ProcessedInputData/waterallocations_longsiteid.csv

https://drive.google.com/drive/folders/1Nzc0cmwtLjnl0V1MY4J4wswHIkAB1iHy

**Comment by tsga** [comment]
So this is no longer a bug, rather a feature that forces the length of the SiteUUID to be < 500 characters long. So change it to a documentation type issue, and close it.
