### ISSUE TITLE
Colorado water rights with no water source info

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#211]
**These water rights have no water source info at all.** 
1. https://westdaat.westernstateswater.org/details/right/COwr_WR3287100C405471

2. https://westdaat.westernstateswater.org/details/right/COwr_WR39095389980A5103709

**Others like this one have, so not sure what's the issue.**
https://westdaat.westernstateswater.org/details/right/COwr_WR3360200A604238

**Comment by amabdallah** [comment]
@rwjam could you please check the CO data system why the state landing page is broken? its the CO system 

https://westdaat.westernstateswater.org/details/right/COwr_WR39095389980A5103709

**Comment by rwjam** [comment]
resolved
