### ISSUE TITLE
TimeframeStart and TimeframeEnd adding "Year" value on import

### ISSUE THREAD

**Issue by tsga** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#22]
The WaDE inputs design specifies that TimeframeStart and TimeframeEnd will have mm/dd format as
01/01 and 12/31

But the imported value in WaDE QA DB has format of 01/01/2020 and 12/31/2020. 

It may be OK, then close the issue.

**Comment by amabdallah** [comment]
Good catch. Right, I dont think there should not be a year there. I'm afraid we introduced this bug in the recent updates. Could you check in the database and see what these two columns are exactly called in the Core_AllocationAmounts_fact table? They might include "ID" at their end which forces the values to be a date format (we dont want that)

**Comment by tsga** [comment]
Yes, they are called "AllocationTimeframeStartID" and "AllocationTimeframeEndID" in the DB

**Comment by amabdallah** [comment]
So we need to reverse a change that was done on these two by mistake. There should not be ID associated with these as the ID means they are joined into the Date table. These fields are not dating format. I'll have to ask DPL to fix it :(

**Comment by tsga** [comment]
This has been added as an issue in WaDE 2 Github pages, so am closing it in the interest of reducing the number of issues.
