### ISSUE TITLE
Water Source Type in WestDAAT

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#223]
In both environments, many black circles do not show up in the legend for water source type. I see many of them have a water source type=WaDE, Blank

I see below dots in Montana, Wyoming, North Dakota, Utah., Mew Mexico, California, and Washington 

### Prod
https://westdaat.westernstateswater.org/?state=N4Ig7gTgJiBcoAcD2BLAdgFwMooF4FM4QYAaEAWwEMEBxCJAVwXQHMiwBnAFQE8FCAvmSoI4oXEiTkAMvgBu%2BADZwALADoAHADYtABg0B2fQFYAnFoBMKiwbKLKGFBgZRCsFQEY1p3VbtI0FicXNwBaD301CwBmDVMVAQEgA

### Staging
https://westdaatstaging.westernstateswater.org/?state=N4Ig7gTgJiBcoAcD2BLAdgFwMooF4FM4QYAaEAWwEMEBxCJAVwXQHMiwBnAFQE8FCAvmSoI4oXEiTkAMvgBu%2BADZwArADoAjADYAHAE4NGgCxaATAAY9OgOwBmU2UWUMKDAyiFYR02ut7zWlqOSGgsru6eALSGGpqmptbWAgJAA

**Comment by rwjam** [comment]
Odd.

Those sites are indeed marked down as "WaDE Blank" on our maptiler file, which is how sites are colored on WestDAAT.  "WaDE Blank" is a recognized WaDE term in our database.

Looking through the map I don't see any other "WaDE Blank" or Unspecified related water source types showing up on the legend.  This might be a question for DPL / Andrew to see if they can see why that category is not showing up on WestDAAT.

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/17555073/99ab5370-904c-49f4-9a80-78a7f35f2c18)
![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/17555073/f09ba61c-c41a-4b09-8816-0181bb3307d4)

**Comment by rwjam** [comment]
At this time, we can't afford to pay DPL for this fix.  Instead, we will have to go back to those wr projects and force the WaterSourceTypeCV values to be a pre-WestDAAT approved value (i.e., Surface Water, Groundwater, or Unspecified) based on interpretation of the state provided source data.

The following wr project's need to be remapped for this fix to take place: AK	CA	MT	ND	NM	OR	UT	WA	WY
