### ISSUE TITLE
Owner classification: Us Dept Of The Interior

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#253]
Two things to consider in the classification algorithm 

1. Let's classify "Us Dept Of The Interior" as United State Of America". 
Here is an example 
https://westdaat.westernstateswater.org/details/right/NMwr_WRSP02849

2. The algorithm needs to be smarter regarding the existence of "USA" in the owner name.  In this example, a private company has "USA" in its name so it got classified as United States of America which is not correct.
https://westdaat.westernstateswater.org/?state=N4Ig7gTiBcoPZgHYFMIGEA2BDAzjglgGb4DGWALvnIjjANogCqi%2B5yAJgAQDK5FyOTnEKcAggFtUpLCAC6AGhD4cAOQzt8AMXwY2EUSUoA3ZDEJYMOZAF9rQA

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/925d5c1f-0f41-4587-a7d5-3c3cd1a4b9bd)

**Comment by rwjam** [comment]
Added "Us Dept Of The Interior" keyword to the United State Of America group.

Will included the following new keywords into “Private” to help cut down on similar issues.  These are keywords I noted in AZwr alone and is not a complete total comprehensive list. I think we can continue to add on to: Amoco, assurance, bank, business, cemex, center, chemical, chevron, christian, church, cocacola, estate, estates, exxon, farley's, farmers, fertilizer, freedom, gold, hallelujah, home, insurance, lc, limited, lllp, minerals, nestle, prayer, production, ranch, ranches, real, scouts, Toyota, Walton, waste, Texaco, Antea, Velcro, Epcor, Confac, Mattamy, Phillip. 

Update AZwr & NMwr to reflect these changes on the uat, will slowly update other states’ water rights to reflect these changes as we continue to review projects and data.
-	https://westdaatstaging.westernstateswater.org/?state=N4Ig7gTiBcoPZgHYFMIGEA2BDAzjglgGb4DGWALvnIjjANogCqi%2B5yAJgAQDK5FyOTnEKcAggFtUpLCAC6AGhD4cAOQzt8AMXwY2EUSUoA3ZDEJYMOZAF9F4rAAcYoAF5w44gDLITGGABZFbEpyAFd2U2gAZgAmADoogEYABgBWVKDqAHNWcMiAWgBORLj-AHYYgDYADmtrIA
-	https://westdaatstaging.westernstateswater.org/details/right/NMwr_WRSP02849


Updated Owner Classification functionality. https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/tree/master/5_CustomFunctions/OwnerClassification
- Changing the default value to “Private”.  Reality is I’d say > 80% of water rights in WaDE would be considered Private.  I think it would better to try and prove the water rights are NOT private.  Blank or unknown water rights are still considered “Unspecified” group.
- Now uses a new Notes_OwnerClassification.xlsx file, which is easier to view and work with.  Easy to add new keywords to search for and new OwnerClassification type groups.  Added instructions on how to add new keywords and groups.  Added color coordination.  Added duplicate error color coding to help key an eye out for duplicate keywords used across groups.  OwnerClassificationField.py now uses the Notes_OwnerClassification.xlsx file for easy dataframe -> dictionary creation. 
- Simplifying the ReadMe for the Owner Classification functionality.  Removed keyword lists.  I think this is starting to scale so much that placing those lists on the ReadMe is getting cumbersome.  Instead, I think it would better to encourage a reviewer &  user to download the Notes_OwnerClassification.xlsx file for easier visualization purposes.
![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/17555073/2479e046-731e-4151-a8df-4f164aa9c4fb)

**Comment by amabdallah** [comment]
I love this Excel table. Did you do it manually? I think it would be helpful to pivot it (swap rows and columns), which makes it easy to show/present as ~20 rows (classifications) and then multiple columns for the values. I then could create comma-separated values to show them in a Word Document for presentations etc

**Comment by rwjam** [comment]
Let's leave the table as is.  It's being used with the code / it's simple to add new items to each list & create new list / verify we want already using the same keyword.

If you need a copy of it for a word doc report, I'd say just copy the xlsx file to your local machine and manipulate it to fit the doc better.
