### ISSUE TITLE
Timeout value of 00:05:00 exceeded by function 'LoadWaterSourcesBatch'

### ISSUE THREAD

**Issue by tsga** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#26]
While importing OR allocation data, I encountered this (intractable) error. I found out (too late) that some of the WaterSourceType entrees may have a space in the text and that may be causing the problem but I don't know for sure. 

Timeout value of 00:05:00 exceeded by function 'LoadWaterSourcesBatch' (Id: '57b2b4d1-4471-4877-ba21-a4210fb37d5a'). Initiating cancellation.

**Comment by amabdallah** [comment]
@tsga could you please move it to WaDE 2.0 repo? it fits better there as it is a bug in the data loader

**Comment by tsga** [comment]
This is not a bug as it is caused by error elsewhere. So close it.

**Comment by amabdallah** [comment]
Great! could you mention here what the error was so we know it if it happens in the future?
