### ISSUE TITLE
Update Montana water rights data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#261]
The state switched to a new system and all of our links to state landing pages now lead to the new system homepage. 
See here
https://westdaat.westernstateswater.org/details/right/MTwr_WR41T21459400

I think the new system is using ESRI feature services but they dont seem to be public. 

I found this other place that seems to support a mass download
https://mslservices.mt.gov/geographic_information/data/datalist/datalist_Details.aspx?did=%7B0303D17E-BD0F-4180-A345-359C61E586F0%7D

Let me reach out to the state's point of contact and ask them what they suggest for us to use.

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/eb37b5ff-90b3-4489-9508-fd12a3aecb84)

**Comment by rwjam** [comment]
@amabdallah did you ever reach out and ask MT if they would we rather use this data?

--------------

Good data.  According to the metadata [link](https://ftpgeoinfo.msl.mt.gov/Data/Spatial/NonMSDI/DNRC_WR/MTWaterRights_Metadata.xml) I think we want to use the more raw "current operating authority" data (WRDIV, WRPOU, WRRES) (versus their administrative purpose data WR1DIV, WR1POU, WR1RES).

Does have WaterAllocationNativeURL, ben use, priority date, good identifiers, start and end dates, source names, owner names, allocation type, legal status type, POD and matching POU data.  Also has water rights associated with a reservoir (Points of Reservoirs?).

One thing I’m not seeing is either a CFS or AF value to use.  If we use this data we would have to make it wade exempt .

**Comment by rwjam** [comment]
Found a source of data from DNR, let's use that one isntead https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/issues/284
