### ISSUE TITLE
Review Idaho (ID) water right data: water source type: reuse

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#266]
Is this a Mapbox bug, or does Idaho have a "water reuse" source type? 

I was looking into example water rights like this one but did not see "reuse" in the state native landing page.  The PODs are in the Colombia River Basin, so I'm not sure how the "reuse" came in.  https://westdaat.westernstateswater.org/details/right/IDwr_WR123A

https://westdaat.westernstateswater.org/?state=N4Ig7gTiBcoEYFMB2CBmBLAxughgGwFUBnBAORwFsEiYBtEAQQHMIsBXPAFzYgQAIAkhFZMcndAHskIALoAacGIQQAyhJ6YEAFQCeAB2p0QAJQRsSshUU5Ka0egS0gFAgCKWQeiQBMACupgQXwB5AmcQdCJSPG90ADF0LmUGTHEANwQYVHwSAF8FChw9GFAALwkJCgAZBAy8GAAOADoAVgAWACYWgDYABj6AZg6Adg7ehoaFPDF0bm9M6E6mtoBGboGpqSZZtnmYAFoVlYGmhpW2gE4B-PAIbxLPCXQkThV0UoWQe4KigHEIdR6Z5MQJgIi6AwgXK5IA

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/5d6ef44a-feec-459e-b640-ec204656bae2)

**Comment by rwjam** [comment]
For IDwr, it's a little tricky in identifying water source type.  We essentially get WaterSourceName and WaterSourcetypeCV from the same column (see 1st img).  For WaterSourcetypeCV we use a keyword search to look for specific values (see 2nd img).  Some of the source values do contain a "Waste" or "Waste Water" value (see 3rd img), which is where we identify a "Reuse" value. [link](https://data-idwr.hub.arcgis.com/datasets/water-right-pods/explore?filters=eyJTb3VyY2UiOlsiV0FTVEVXQVRFUiIsIkNIUklTVElBTiBHVUxDSCBXQVNURVdBWSIsIldBU1RFIERJVENIIiwiRkFSR08gV0FTVEVXQVkiXX0%3D&showTable=true).

We could go back and change that "Reuse" value in our keyword search and tag it with a "Surface Water" value, if that is a better approach.
![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/17555073/e3e43516-6397-4c07-8645-addff55e077e)
![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/17555073/77567860-6ddf-422f-aa2d-5f82836f8987)
![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/17555073/17b925e6-b4df-4e27-a67e-81c8aa70d9e2)

**Comment by amabdallah** [comment]
This is very interesting! Thanks for looking into all this. Let's discuss more over a Zoom call, and I would probably prefer to ask Idaho if they could add water source type themselves. Wastewater is interesting, for sure. "Waste" alone may actually indicate return flow, which is different from urban wastewater/treatment and reuse.

**Comment by rwjam** [comment]
List of distinct water source names from the IDwr data.

[IDwr Distinct Water Source Names.xlsx](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/files/13606141/IDwr.Distinct.Water.Source.Names.xlsx)

**Comment by amabdallah** [comment]
Thanks! so I see these unique native water source names we classified for "reuse." I think its reasonable to keep the red color ones as "reuse." Not sure what to do with the other ones. Wasteway appears to be a ~name

https://files.slack.com/files-pri/T20SYLSD9-F0696TJRJRH/image.png

**Comment by amabdallah** [comment]
We decided to follow this:

Reuse = Treated Municipal Wastewater, Waste Water, Wastewater
Surface Water = the Wasteway names.

**Comment by rwjam** [comment]
- Redownloaded the source data (POD and POU)
- updated water source type cv to match above notes
