### ISSUE TITLE
Import Nevada's water rights data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#27]
A place to start 
http://water.nv.gov/waterrights.aspx?rights=Water%20Rights%20Databases

http://water.nv.gov/mapping.aspx?mapping=Mapping%20Application%20Links

POD datasets
http://water.nv.gov/mapping.aspx

POD and POU
http://webgis.water.nv.gov/Html5Viewer/Index.html?configBase=http://webgis.water.nv.gov/Geocortex/Essentials/REST/sites/NDWR_Water_Rights/viewers/NDWR_Water_Rights1/virtualdirectory/Resources/Config/Default

**Comment by tsga** [comment]
Couldn't find a way to bulk download the water rights data (the data seems to exist but requires specifying individual criteria such as owner name, dates ...). Attempt to export layers from the webgis failed.

**Comment by amabdallah** [comment]
http://water.nv.gov/permitinformation.aspx?app=1440

**Comment by ryjamesj** [comment]
Can confirm that could not download bulk download on water rights data.

Might be able to spread it out though and download each unique element individually (e.g. POD Commercial, POD Irrigation, etc).  Each download comes with a) 'Permit Database Information', and b) info about the selection table used.

**Comment by rwjam** [comment]
Update on Nevada Water Rights' data.

Data already downloaded and stored here: https://drive.google.com/drive/u/0/folders/1THOWWT6eK3mWAIMD_mWjncF2fjwTqXY4


Their Links:
Check links for definitions and metadata.
1. 1. https://ndwr.maps.arcgis.com/home/item.html?id=0d050f7b79724404b80bf29589f67363
2. https://arcgis.shpo.nv.gov/arcgis/rest/services/Water_Resources_Public_Data/WaterRights_POD_POU/FeatureServer
3. https://arcgis.shpo.nv.gov/arcgis/rest/services/Water_Resources_Public_Data/SE_HydrographicBasins/FeatureServer
4. http://water.nv.gov/CodeDefinitions.aspx

**Comment by rwjam** [comment]
Finished mapping and uploading.  Internal WaDE 2.0 system of 'PrimaryBenficialUse' **MUST** be filled out before the WaDE 2.0 db will update the BeneficialUseCV tables.

**Comment by rwjam** [comment]
Load NV POU data.

**Comment by amabdallah** [comment]
PODs
https://data-ndwr.hub.arcgis.com/maps/NDWR::water-rights-points-of-diversion/about

**POU**
https://data-ndwr.hub.arcgis.com/datasets/water-rights-places-of-use/explore

**All(?) these yellow POUs on the east side of Nevada have PODs in the West.**
https://westdaat.westernstateswater.org/?state=N4Ig7gTiBcoIYBsEHsDGcAuBLZA7A8mLgKZTQgYC2YcIANCAA7IICeCWJMA2gLoO4EAEywAxLAgykAIplqwQCTFgwBXIcRi5VSBilwBzFes3RtukCIjFU2PAGcYAZgZC5ABWScMj6AHYAXwCGSjhGGFAAL2RkSgAZYgA3YgQYADYAOgAOJwAGXIBWLNyATiyAJhLypwAWLL1lNQ0YGtyMwqdygEY-ErSSmr8u-r08IybTAFouroKMkpKCpwK-Pyy66vLgkEpfEHsMa2IfScSZkACgA

**Comment by amabdallah** [comment]
Bug(?) why this POD and POU are way too far from each other?
https://westdaat.westernstateswater.org/details/right/NVwr_WR68681
