### ISSUE TITLE
Review Washington (WA) water right's amounts units 

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#270]
This could be an issue with WA data, not ours, but it is worth double-checking before I contact WA's folks.
**Problem**
This domestic water right seems very big (too big to be true). So I looked into their landing page and scanned documents. The WA landing page has confusing units. The scanned document shows 16 GPM flow and 2.5 AF per year. 

**Question**
Would you check the downloaded data and trace this water right there to confirm what the issue is? 

**WestDAAT** 
https://westdaat.westernstateswater.org/details/right/WAwr_WR2051274

**WA landing page**
https://appswr.ecology.wa.gov/waterrighttrackingsystem/WaterRights/WaterRightRecord.aspx?waRecId=2051274#no-back-button

**Scanned document (Sourth of Truth)**
https://appswr.ecology.wa.gov/docs/waterRights/A463/A4632977.pdf

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/02e07c9e-237c-40a4-80d1-57c369d68e7e)

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/a5df9480-e5fb-454c-a2e1-dce37ee6be16)

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/13edf5d0-5d11-41fb-a5a9-04f53fc83ff7)

**Comment by rwjam** [comment]
This looks like to be an issue with the WA data.  A recent inspection (06/26/2024) from the source download [link](https://fortress.wa.gov/ecy/gispublic/DataDownload/wr/GWIS_Data/) showed the same results we have in WaDE.  We join WR_Doc_POU1.shp (for POU shp) and Person_Plus_EXTRACT_FromWRTSnotGWIS to interpret POU info.  The data reports it as both an Active water an a IFlow, MT, IR (i.e., Irrigation) for purpose (see img).



![Image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/17555073/f6dac100-e92e-4964-9805-6c73a034f8a8)
