### ISSUE TITLE
Review Utah (UT) water right: why waterfowl habitat not showing up after "Other" ben. use?

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#277]
The forest service folks raise the question why our landing page shows State Beneficial Use=Irrigation and Other and doesn't not show waterfowl habitat as in Utah landing page.

It could be how the raw source data came to us. Let's confirm what's going on.
Ideally, we want show: Irrigation and Other: Waterfowl Habitat

https://westdaat.westernstateswater.org/details/right/UTwr_WR291014

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/771b6076-a5ed-4fe3-9ef9-10a982a04350)

**Comment by rwjam** [comment]
This is an example of how the state's are providing us with the data. For UTwr we derive the beneficial use from the **USES** input.  In this specific case, the ben use comes in as "IO" which translates to Irrigation, & Other.  We would have no way of knowing that Other, in this case, would mean Waterfowl Habitat, without Utah telling us directly.  I suspect Other is just a blanket term used by UT as a filler when the exact use is uncommon.

Link to POD data [link](https://opendata.gis.utah.gov/datasets/utahDNR::utah-points-of-diversion/explore?filters=eyJXUk5VTSI6WyIyOS0xMDE0Il19&location=39.485303%2C-111.591274%2C-1.00&showTable=true)
Link to POD metadata [link](https://www.arcgis.com/sharing/rest/content/items/5d530e62e6ca42528dd13e0a453a3b73/info/metadata/metadata.xml?format=default&output=html).

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/17555073/acd83af7-b5bc-49ed-92cb-ac3163e5f9f0)
![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/17555073/5944cd04-2b39-448d-a207-1d3186e200c1)

**Comment by rwjam** [comment]
Utah itself does not
