### ISSUE TITLE
New Utah (UT) Water rights administrative boundaries 

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#279]
Apply to both surface and groundwater sources.

https://opendata.gis.utah.gov/datasets/utahDNR::utah-water-right-areas/about

**Comment by rwjam** [comment]
I suspect this is for surface water, as it pertains to surface drainage areas?

**Comment by amabdallah** [comment]
Good point. Let me ask and double check

https://waterrights.utah.gov/contact.asp

**Comment by amabdallah** [comment]
@rwjam based on Jim Reese's response below, let's assign this overlay to both surface and groundwater sources.



> Groundwater and surface water rights are all administered together, although in some areas there may be different policies for surface and groundwater, such as whether new appropriations are allowed. Regional offices do deal with both surface and groundwater rights

**Comment by rwjam** [comment]
These should share the same reporting unit areas (ids) as [New Utah (UT) groundwater policy regulatory overlays Data#283](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/issues/283)
