### ISSUE TITLE
Import California water rights data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#28]
Here is the CA water rights database access portal. It does not seem to support a mass download but pending a response from Greg Gearhart.
https://www.waterboards.ca.gov/waterrights/water_issues/programs/ewrims/

Here is a cool dashboard for CA water rights. We need to check if the Tableau workbook includes the Excel sheet that contains all the data 
https://public.tableau.com/profile/rafael.maestu#!/vizhome/WaterRightsTypesbyWatershedHUC6SENIORRIGHTS/HUC6Dashboard

**Comment by tsga** [comment]
This document "EWRIMS MASTER FLAT FILE METADATA DRAFT 1-17-20.pdf" says, “Data dictionary [is] pending”, and some of the terms, e.g. LOCATION_METHOD for Sites.CoordinateMethodCV, have been entered into the ‘sites.csv’ ‘ as they are’. If these terms need mapping to different values by a dictionary, then we may need to revise the Sites table later.
