### ISSUE TITLE
New Utah (UT) Groundwater Management Areas regulatory Data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#283]
Type: regulatory: Water Source: Groundwater

Background
https://www.waterrights.utah.gov/groundwater/

Map
https://www.waterrights.utah.gov/gisinfo/maps/agwpol.pdf

GROUND WATER MANAGEMENT PLANS (i.e, URL for each polygon)
https://www.waterrights.utah.gov/groundwater/ManagementReports/ground.asp

Shapefile: Shared by email on 12/07/2023, from Jim Reese at Utah DWRi

[ground_water_policy_polygons.zip](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/files/13602832/ground_water_policy_polygons.zip)

**Comment by rwjam** [comment]
These should the same reporting unit areas (id) as [New Utah (UT) Water rights administrative boundaries #279](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/issues/279)
