### ISSUE TITLE
New Colorado site-specific diversions / withdrawals water use data

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#293]
based off this project: https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/issues/60

should use same links to download data. Let's try to connect this timeseries now with the water right IDs.

Also review this issue (maybe new POU shp files to work with): https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/issues/307

**Comment by rwjam** [comment]
We want to try and tie individual water right record sites to monthly water use site records.  Issue that it looks like CO Rest API service returns the TOTAL USE per site and does not distquish the amount for each water right in the event that a site has M:M water right records.

For a temp fix, we can just focuse on the sites with a single water right record tied to them.

- using these sites as our base for water right information: [link](https://data.colorado.gov/Water/DWR-Water-Right-Net-Amounts/acsg-f33s/data)
- want to tie this monthly timeseries record: [link](https://dwr.state.co.us/Rest/GET/Help/DivRecMonthGenerator)

------------------------------------ 
Issue that we can't get the API to work. Do we need a new api key? Adel to reach out to CO and ask

**Comment by amabdallah** [comment]
I looked a bit more into the API token for Colorado. You need to sign in (using your work Gmail) and they generate a new key for you.
![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/d7bbc193-cca9-419c-98e2-71f47895ae09)

**Comment by rwjam** [comment]
Buried note in older work that says "Diversion records do not connect to the Water Right."  Possible that there is no way to connect using water right information: [link](https://data.colorado.gov/Water/DWR-Water-Right-Net-Amounts/acsg-f33s/data) to monthly timeseries record: [link](https://dwr.state.co.us/Rest/GET/Help/DivRecMonthGenerator)

**Comment by rwjam** [comment]
Finished updating
https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/commit/b85bee30060a507c551bd887fde9f026cde414c0

**Comment by rwjam** [comment]
Finished updating
https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/commit/b85bee30060a507c551bd887fde9f026cde414c0

**Comment by rwjam** [comment]
We are missisng this 'bonus' script & any documentation on how this was accomplished.  I need to track that down / recreate it by hand if need be.
_
> This can be done with a bonus script to remove time series records from input files where groupby(AssociatedNativeAllocationIDs) > 1 per site.
_

**Comment by rwjam** [comment]
Actually, it looks like we did not create a bonus script for this, and instead performed this limitation during the initial download of the time series data.

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/17555073/6a567f7b-9bce-4f3e-ad5e-e9c42e507763)
