### ISSUE TITLE
Review AKwr owner classification - remove BOR

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#297]
Not sure what's the best way to deal with this issue but let's remove all Reclamation Classfications in Alaska. BOR in Alaska is an abbreviation to Borough :) 
**Examples**
1. SITKA CITY AND BOR  its for Sitka city and borough, Alaska.
2. FAIRBANKS NORTH STAR BOR is for Fairbanks North Star Borough
3. KENAI PENINSULA SCHOOL BOR DIST is for Kenai Peninsula Borough School District

https://westdaat.westernstateswater.org/?state=N4Ig7gTiBcoPZgHYFMIGEA2BDAzjglgGb4DGWALvnIjjANogBCArhMlswAQBKyJ2AWwpVEnABQBVAMqNuAShAAaEL35YhlapzTVyELCXJwoAXWU5yFZLWgMAggGkQZkPhwA5DABN8AMXwY5Kh2hvgAbsgwhFgYOMgAvspCAA4woABecHACADLIERgwAJwAdAAcAIwArABsVRUA7NUAzFUALK3NytiU5MxekdA1beUADDUATEXd1ADm%2BH0DMAC0FW0NJeujDVXx8UA

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/cef422ce-3736-4e30-aeed-0b2e0341acea)

**Comment by rwjam** [comment]
BOR is traditionally an abbreviation for "Bureau of Reclamation". However, digging through the WaDE AllocationOwner looking for instances where this occurs, looks like it doesn't come up much as "BOR" for Bureau of Reclamation tends to be accompanied by other elements.  Seems like an easy fix to help prevent this in the future is to be more specific with our word matching (see image below).  This change will solve the above AK issue.

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/17555073/e66378e2-2337-4cd9-930d-bed2b10abff4)

**Comment by rwjam** [comment]
code commit: https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/commit/36423642231dccd0a03c58f1beb5557aa2c6c805
