### ISSUE TITLE
Evaluate Colorado (CO) water rights irrigation POUs

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#307]
@rwjam would you please review the metadata of these two shapefiles and see if it can be related to their PODs or water rights? 
https://cdss.colorado.gov/gis-data/gis-data-by-category

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/fdc93035-3165-4d6a-8020-3f484e0f1d26)

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/65a1f887-88b2-43a6-913e-aac3bd022ec3)

**Comment by rwjam** [comment]
**Irrigated Lands**
- Broken up into Divisions (1-7).
- This data tends to have wells (points), canals / ditches (lines), and land use areas (polygons) separated out in 5 year increments (which I think means they are tracking the change in ownership / use over time).  We are only interested in the land use polygons for 2020 (latest) and can new join those to our known COwr data.
- The trick is, I don’t see anything similar to a parcel number / pou id in our [COwr source data](https://data.colorado.gov/Water/DWR-Water-Right-Net-Amounts/acsg-f33s/data). So I’m not sure how we would join it to anything within the land use 2022 polygon info.


**DWR Irrigation Ditches**

- This only contains canal / ditches (lines) information.  Nothing that can be tied to a wr / of interest to WaDE at this time.
