### ISSUE TITLE
Utah water right related withdrawals

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#324]
Utah has water right related withdrawals as (Irrigation use). I looked here but no idea how this works. The metadata fields seem to indicate Section/Quarters and I'm seeing time series data. Let's discuss and then I can reach out to the Utah folks.

https://www.waterrights.utah.gov/cgi-bin/pubdump.exe?DBNAME=WRDB&SECURITYKEY=wrt2012access

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/9413c0b9-4c68-4a53-b9db-58e75a0fb677)

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/b22b508f-3dea-4b06-92c1-b563851d5cbd)

**Comment by rwjam** [comment]
- Unfortunately, I'm not sure the metadata on this info.  I think you are right and that the IRR_NWNW -to- IRR_SESE info get into Section/Quarters, or surveying elements.  I'm not seeing anything that looks like a time stamp value, a flow, or a volume within that data either.
- Looks like most of the returned information is also 0 (see img).

![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/17555073/2526264a-67fc-4895-87ed-366dfdf7cb0f)

**Comment by rwjam** [comment]
At this time, there doesn't appear to be a good way to pair timeseries water use data to any wr (pod or POU) information.  Following up on Jim's comments...
- this [PUBDUMP Database table dump Utility](https://www.waterrights.utah.gov/cgi-bin/pubdump.exe?DBNAME=WRDB&SECURITYKEY=wrt2012access) service is out of date and was used mostly for legal place of use (no timeseries data, no related wr information).
- The [Water use Data Portal](https://waterrights.utah.gov/asp_apps/waterUseData/setFilters.asp) does contain timeseries POD (source) and related POU (system) data, but it currently does not match / pair it with any wr related information.
  - We are still going to use this data as site-specific public supply data, not related to a wr. (i.e, UTssps).
  
  
Sounds like UT is currently working on a "Water Rights Network" project that is intended to connect measurement data, water right data, and place of use data together.  We will keep an eye out for this.
