### ISSUE TITLE
Review CA groundwater rights (i.e., well completion report)  

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#332]
**1. Let's update the organization name in GitHub and the database for CRNA groundwater wells water rights data to the California Department of Water Resources.**
Besides Jennifer Stricklin as contact info, let's also add:
Eric Senter
Sustainable Groundwater Management Office
California Department of Water Resources
Office: [916.902.7008](tel:9169027008)
Mobile: [916.340.4433](tel:9163404433)
[eric.senter@water.ca.gov](mailto:eric.senter@water.ca.gov) 

**2.. I figured out why CA has these outlier flow values for their wells. It is a digitization error (very very likely)** 
See this scanned document here. In the screenshot below, you'll see commas between three values 200,315,435. I think these three separate values correspond to the "Total draw" values. They got digitized as a thousand commas. They could be three separate pumping test runs. I need to reach out to CA folks and double check. In the meantime, we cannot do much about them because CA needs to fix this data at their end. So We probably should remove all flow values from this dataset. So put zero for now.
**Digital**
https://data.cnra.ca.gov/dataset/well-completion-reports/resource/8da7b93b-4e69-495d-9caa-335691a1896b?filters=WCRNUMBER%3AWCR2016-016639

**PDF**
https://cadwr.app.box.com/v/WellCompletionReports/file/466474317042
![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/cffe8982-6425-492f-8cd4-313e5cfc8866)

**3. Something is not right in how the final unit is stored in WaDE.** 

The unit conversion factor [here ](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/blob/master/California/WaterAllocation_WaterUse_CSWRCB/1_CSWRCBwr_wu_PreProcessDivisionAndWithdrawalSites.ipynb)is correct:
```
    if unit == "Gallons per Minute":
        CFS_Value = val / (448.83117)
```
Which is the same as 1 gpm=0.002228 CFS

**Example1** Native ID =WCR2015-013287
WestDAAT shows this: Assigned Flow (CFS) =682,511.4596352499 
https://westdaat.westernstateswater.org/details/right/CNRAwr_WRWCR2015013287

The source for the same native number shows a yield as 255,075,100 GPM
https://data.cnra.ca.gov/dataset/well-completion-reports/resource/8da7b93b-4e69-495d-9caa-335691a1896b?filters=WCRNUMBER%3AWCR2015-013287

If you convert 255,075,100 GPM to CFS, that is 255,075,100*0.002228 =568,307.3228 CFS but WestDAAT shows 682,511.4596352499 

**Example1** Native ID =WCR2016-016639
The same issue exists which seems to me there is a systematic conversion error but not sure where it is coming from because the conversion factor in the code is correct. Could it be overwritten by accident in the code by a different factor?
https://westdaat.westernstateswater.org/details/right/CNRAwr_WRWCR2016016639

The source for the same native 
https://data.cnra.ca.gov/dataset/well-completion-reports/resource/8da7b93b-4e69-495d-9caa-335691a1896b?filters=WCRNUMBER%3AWCR2016-016639

**Comment by amabdallah** [comment]
Eric Senter, Sustainable Groundwater Management Office,California Department of Water Resources responded:

> Your interpretation of what is going on with these yield values is probably correct. The form we have for drillers to input well production test data is limited to only one value, but the driller entered several values. Our system appears to have concatenated the three values into a single value. My guess is that this was a step-drawdown test conducted over two hours at three different rates with three associated drawdown values. I wouldn’t put too much faith into the production amounts, as the test was only two hours long, not enough to determine the long-term production. Also, it’s quite difficult if not impossible to measure groundwater level drawdown using an airlift test. More reliable yield values can be determine using a submersible pump for at least 24 hours.

@rwjam so let's go ahead and remove all flow values for this dataset from WaDE, for now. These are more of groundwater well capacity values which are different than the permitted rights. In the future, we need to add groundwater well metadata like capacity, depth, aquifer name, etc, to the AllocationAmounts table.

**Comment by rwjam** [comment]
We removed CA groundwater rights, as they were well driller logs not legal permits.
