### ISSUE TITLE
Error when updating Utah Allocation Data

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#34]
Ran into issue with trying to concatenate values for 'AllocationOwner' and 'AllocationCommunityWaterSupplySystem' when groupby NativeID for Allocation_facts.  Both exceed the char(250) limit.

**Comment by ryjamesj** [comment]
NativeID '89-275' appears to have a rough estimate of 174 of PoD.  Results in char(length) with SiteUUID that exceeds 250 (was 1719) for me for Allocation_facts sheet.

https://maps.waterrights.utah.gov/EsriMap/map.asp?layersToAdd=PodSearch&q=00-138#89-275

**Comment by ryjamesj** [comment]
Issue of 'GeneratedPowerCapacityMW' causing a 'Cross Group Not Valid' error when importing.  Not known why.

**Comment by amabdallah** [comment]
I think DPL fixed this "Cross Group Not Valid" issue. See here: https://github.com/WSWCWaterDataExchange/WaDE2.0/issues

But we should make sure it is fixed as we load more data

**Comment by amabdallah** [comment]
@rwjam should we close this issue?
