### ISSUE TITLE
Texas site-specific water use data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#35]
TCEQ publishes the monthly self-reported site-specific water use data in three variables: diverted, consumed, return flow for each water right (except wastewater treatment plants)

https://www.tceq.texas.gov/permitting/water_rights/wr-permitting/wrwud

Mapping the data to WaDE site-specific data will require lots of pivoting and manipulation.  For now, lets only target this data "From 2000 through 2014"

![image](https://user-images.githubusercontent.com/3268971/77186689-e8b57200-6a98-11ea-8e56-90fdc52835d9.png)

**Comment by rwjam** [comment]
> TCEQ publishes the monthly self-reported site-specific water use data in three variables: diverted, consumed, return flow for each water right (except wastewater treatment plants)

Of those three variables, which should we focus on? diverted, consumed, return flow?

At the moment, WaDE 2.0 Site Specific data looks for an Amount value, which has a lose definition of 'The aggregated variable amount."  I think we can take us this in either two directions: 1) break up the WaDE 2.0 Amount term into more specific values, 2) break this TCEQ data into three separate data sets with a method types of diverted, consumed, return flow.

**Comment by amabdallah** [comment]
Let's discuss this one. It looks similar to the UT M&I data. Its 

https://www.twdb.texas.gov/waterplanning/waterusesurvey/serviceboundaryeditor.asp

![image](https://user-images.githubusercontent.com/3268971/107709600-b26d7c00-6c82-11eb-8928-38deeb985a32.png)
![image](https://user-images.githubusercontent.com/3268971/107709740-f19bcd00-6c82-11eb-8ffb-6d418d4101f9.png)


There must be a way to join the shapefile info with the time series historic data file (somewhere at the link below). We probably need to chat with the TWDB to see what they suggest. I recommend looking into all these to prepare for the call and ask them questions. 
   
![image](https://user-images.githubusercontent.com/3268971/107711059-5277d500-6c84-11eb-83ee-918d92bf8f8c.png)

**Comment by amabdallah** [comment]
Out point of contact at TCEQ shared an Excel file with us that includes all their data.

**Comment by rwjam** [comment]
Data provided here is outdate.  Please see new issue to work on.  https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/issues/89

**Comment by amabdallah** [comment]
I'm opening this issue because it contains relevant info.
http://www.twdb.texas.gov/waterplanning/waterusesurvey/estimates/index.asp
If you click at this link as in the screenshot below, TWDB does now seem to share the aggregate water withdrawal per "city" or as they call it "Public Water System" per water source type. This fits what USGS wants at the POU level. So this data might be a better fit for WaDE because of the sensitivity of the wells locations for them. 

![image](https://user-images.githubusercontent.com/3268971/147984086-4a5db79a-a290-4c7b-91ce-bb4c34d9ca1e.png)

**Comment by amabdallah** [comment]
So the Excel file is for aggregate POD data per water source type.  There is a monthly time series data from 1971-2020 attached to each POD. We can define unique water sources from all the data and reuse them across the sites.
The shapefile is the POU sites that are related to the aggregate PODs in the Excel file. In this case, a POU site has no provided time-series data.

I'm not sure what coordinates to include for each POD site. We could use the centroid of the water source name such as reservoirs or groundwater aquifers but that will be a lot of work and there are "unknown" water source names which we won't know. Also, aquafers like the Ogallala aquifer can be giant and their centroid might be outside Texas (no idea). I suggested before using the centroid of the POU for a POD coordinates but now I don't like this idea for two reasons: 1) in visualization, it won't show a line between the a POU and POD because they are on top of each other, 2) there seem to be many aggregate POD sites (e.g., GW#1, GW#2, SW#4, Reuse#5) supplying a POU. So all of them would be on top of each other. 


![image](https://user-images.githubusercontent.com/3268971/148257538-23e68002-da32-4820-bedb-9cc6b4426691.png)

**Comment by amabdallah** [comment]
The best solution I could think of is that we use the centroid of the POU and then add a radial distance from it for each aggregate POD site like this example. I'm not sure how that could be automated in ArcGIS, if at all.

![image](https://user-images.githubusercontent.com/3268971/148262812-e3f1a574-01a9-4cc8-88d7-bccbbf1f933a.png)

**Comment by rwjam** [comment]
We also want to pair the water use (new) with the intake data.

![image](https://user-images.githubusercontent.com/17555073/152018892-6a70b05d-fc71-4d90-95b5-64fee1e5fa3e.png)

**Comment by amabdallah** [comment]
I'm opening this issue as there is a new relevant data source 

[Water Service Boundary Viewer](https://www3.twdb.texas.gov/apps/waterserviceboundaries)

Public Water System layer: relatively new. It seems that each public water system identifier in this layer can be joined with the  Water Service Boundary Viewer to connect polygons (POUs) with intakes and wells (PODs)
https://gis-tceq.opendata.arcgis.com/maps/TCEQ::public-water-system/about

**Comment by rwjam** [comment]
Not sure if relevant any more.  There appears to be no way to export this an externa csv / shp file.  The [ESRI Extract Data (Map Viewer)](https://doc.arcgis.com/en/arcgis-online/analyze/extract-data-mv.htm) tool does not work.  It appears the owner (TCEQ) has not allowed this data to be exportable in their ESRI Online settings.  We can only make a copy of it to view to our own ESRI online service.
