### ISSUE TITLE
Import Kansas water rights data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#37]
**Data dictionary** 
http://hercules.kgs.ku.edu/geohydro/ofr/2005_30/wimas_ofr2005_30.pdf

**Manual query** 
http://hercules.kgs.ku.edu/geohydro/wimas/query_setup.cfm

**I like this legal disclaimer** we should use it for their data and expand on it from other states for all WaDE data
http://hercules.kgs.ku.edu/geohydro/wimas/index.cfm

**Comment by rwjam** [comment]
Was able to work though their WIMAS and accesses Groundwater and Surface Water water right info.  Was able to mass download to csv.  Available data is very expensive and has MOST of what we need.

Mass download however appears to be missing any quantity data (no CFS, no AF).

**Comment by amabdallah** [comment]
So after some digging, I found a way to download water rights with their quantity. 

https://geoportal.kgs.ku.edu/geohydro/wimas/query_results.cfm?active=off&theStartRow=15051&theOrderBy=right_type,%20wr_num

The first screenshot shows all the water rights in the system. Next, clock at Summarize Quantity. Then the second screenshot shows how you can download the water rights that do have a quanity. The downloaded text file is a CSV format. So hopefully we should be good to go and import Kansas water rights now 

![image](https://user-images.githubusercontent.com/3268971/100144191-a7f5d000-2e53-11eb-853c-b0e02ba73193.png)


![image](https://user-images.githubusercontent.com/3268971/100144290-d1aef700-2e53-11eb-9f8e-2d22e107774f.png)

**Comment by rwjam** [comment]
Was able to repeat outlined steps (see above) and saved a csv cop of the data to local machine.  

Data native column headers aren't easy to decipher, going to need to track down terminology and abbreviation translations.

![image](https://user-images.githubusercontent.com/17555073/103694959-01741300-4f59-11eb-8bee-e6e1ed2b1358.png)

**Comment by rwjam** [comment]
Data imported into wade.  Waiting for agency review.
