### ISSUE TITLE
Nebraska aggregate data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#40]
Start here and read this one
https://nednr.nebraska.gov/insight/about.html

Check this data 
https://nednr.nebraska.gov/insight/

Zoom in to a basin and toggle between the different tabs and drop-down menus. Download CSV data. We probably need to reach out to the DNR and ask them if there is another way to mass-download the data for the basins and variables at once.
![image](https://user-images.githubusercontent.com/3268971/80843953-c26c1180-8bc2-11ea-98a1-28b4a3a91a1a.png)

**Comment by rwjam** [comment]
Looks like the shapefile downlead option has the supply and demand values imbedded in the tables.  However, I don't see a ReportYearCV value anywhere on the NE website / data to use with this.
![image](https://user-images.githubusercontent.com/17555073/122438237-bd4d5b80-cf57-11eb-89ee-2fa43e50b56b.png)

**Comment by amabdallah** [comment]
Interesting, is that average data then? I'll ask them. What other metadata we may need that they dont have?

**Comment by rwjam** [comment]
Was able to find a more comprehensive data option for both basin and Sub basin, in the MODELING DATA -> 2015 - > FinalFiles.   These files do report water supply & demand value for 1998 - I think we can use the following values....

- SuppyTotal_NonPeak = supply


![image](https://user-images.githubusercontent.com/17555073/122465306-30b19600-cf75-11eb-814f-a5632ac524df.png)

**Comment by rwjam** [comment]
<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:///C:/Users/rjame/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel="File-List" href="file:///C:/Users/rjame/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>





GWCIrrigation_Annual
--

**Comment by rwjam** [comment]
Found some more time detailed water data files for both basin and subasin, in the MODELING DATA -> 2015 - ? FinalFiles. Data has supply and demand data for 1988 - 2012.  I think we can use the following fields....

Year = ReportYearCV
Basin = reporting area name
SupplyTotal_Annual = total supply amount
SWDemandTotal_Annual = total surface water demand
GWCIrrigation_Annual = groundwater amount for ben use irrigation
GWCMunicipal_Annual = groundwater amount for ben use municipal
GWCIndustrial_Annual = groundwater amount for ben use industrial
GWIAcres = Amount of acreage estimated to be irrigated by groundwater.
SWIAcres = Surface Water Irrigated Acres
COIAcres = Amount of estimated acreage identified as having the potential to be irrigated by both groundwater and surface water (note: doesn't appear to be the sum of GWIAcres & COIAcres).

![image](https://user-images.githubusercontent.com/17555073/122466848-0c56b900-cf77-11eb-9ee4-6e6ece61ed7d.png)

**Comment by amabdallah** [comment]
Great! I think it would be useful to map this to WaDE and import it if possible to see if there is anything else we need from NE folks before our call with them in early July.

**Comment by rwjam** [comment]
Having difficulty determining how to map out the INSIGHT data into WaDE, too many fields to work with.  Data and documentation saved [here](https://nebraska.sharefile.com/share/view/s37d4602190144d1b/fo7a1842-9396-4d4b-a0d1-a0084aa0de8c), need to spend some time reviewing.  Adel to reach out to Shea Winkler for some basic answer and questions.

Questions we have...

- Difference between **surface water consumptive** use in both supply and demand tabs?  How do they relate?
- What is part / what makes up the **Total-Non-consumptive Demand** & **Net Surface Water** Loss bars in the demand plots?
- Difference between **groundwater **depletion** (supply tab) and consumptive use** (demand tab)?

**Comment by rwjam** [comment]
Current plan is to do the following...

Variable
•	Supply – groundwater annual, Model, WSType groundwater
•	Supply – surface water annual, Model, WSType surfacewater
•	Demand – groundwater annual, Model, WSType groundwater
•	Demand – surface water annual, Estimated Appropriation, WSType surfacewater
•	Demand – Total, Non-Consumptive Demand, WSType both
•	Demand – Net Surace Water loss, WSType both

**Comment by rwjam** [comment]
Revisiting how to map out NE ag data to match the updated timeseries approach.  Here is the current idea to build a VariableSpecificCV...

AmountInput |   | WaterSource | AggregationInterval | VariableCV | Beneficial Use
-- | -- | -- | -- | -- | --
SWDTotal_Annual |   | Surface Water | Annual | Depletion | Total
GWDP_Annual |   | Groundwater | Annual | Depletion | Total
GWCTotal_Annual |   | Groundwater | Annual | Consumptive Use | Total
SWDemandTotal_Annual |   | Surface Water | Annual | Demand | Total
GWCIrrigation_Annual |   | Groundwater | Annual | Consumptive Use | Irrigation
GWCMunicipal_Annual |   | Groundwater | Annual | Consumptive Use | Municipal
GWCIndustrial_Annual |   | Groundwater | Annual | Consumptive Use | Industrial



There are lots of other time series we could also utilize (e.g., Hydropower, NetEvaporation, Streamflow, etc).  Looks like NE still hasn't created good meta to work with, hard to trace back and describe exact what the data is.
