### ISSUE TITLE
Import Montana Water Rights Data

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#43]
Use the following steps to obtain MN water rights data.  This will require access to an active ArcGIS Pro license and software.

1. From the Catalog Pane View menu, enter a 'new arcgis server'
2. Use the following url (PM Adel or Ryan if you need password and account info): https://gis.dnrc.mt.gov/arcgis/rest/services/WRD/WRD_WaDE/FeatureServer
3. Catalog -> servers -> FeatureServer on gis.dnrc.mt.gov -> WRD -> drag WRD_WaDE to empty map.
4. Export WRD_WaDE attribute table to csv and / or copy attribute table to csv.

**Comment by rwjam** [comment]
Note: Do not post raw MN water rights data to GitHUB page / Google Drive folder,

There's a little legal issue of MN not wanting to have their raw csv files and data available on the web for the public.  This is only an issue with the raw data from the above url, is should not be an issue once it has been logged into the WaDE 2.0 system, as at the point we have taken responsibility for that data and information

**Comment by rwjam** [comment]
Conventional approaches to get this data don't seem to work.  We have tried the following.

1. Saving map to our portal, no option to down as csv is present
2. Adding feature service to ArcGIS Pro -> exporting table.  Always crashes at 6% with either a Error 000210 (The output cannot be created. Potential reasons include data locking, an incorrect path, and limited access rights.) or an Error 999999 (Something unexpected caused the tool to fail).

This is probably something we need MN to solve for us.

**Comment by rwjam** [comment]
Data uploaded. Waiting for agency review.

**Comment by amabdallah** [comment]
Native ID
40C 137676 00

This is a tricky URL structure because we need to replace spaces in the water right with %

http://wrqs.dnrc.mt.gov/ResultsWS.aspx?search=simple&index=8&wrnumber=40A%2057385%2000&status=ACTV!SEVR

**Comment by rwjam** [comment]
Looks like we can try and use the provided **WR_NUMBER** in the source data.  Playing around with their Simple Search system, it looks like the **WR_NUMBER** is broken up into Basin Code + value in 2000 + another value in 2000 (see image).
![image](https://user-images.githubusercontent.com/17555073/233190422-f3d00466-dbad-487f-b3ff-a9ac601ff52d.png)

**Comment by amabdallah** [comment]
1. Let's remove spaces from MT UUDs
2.  LEt's update the **Applicable Resource Type** from Surface Ground Water into Surface Water and Groundwater

**Example** 
https://westdaat.westernstateswater.org/details/right/MTwr_WR41S%20140365%2000

**Comment by rwjam** [comment]
This issue has been resolved.
