### ISSUE TITLE
Utah water use data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#46]
There is a download button for all data using CSV. Output unit should be either acre-feet or gallons (something to discuss)

Years range 1957-2019
Data 
https://waterrights.utah.gov/asp_apps/waterUseData/setFilters.asp

Metadata (click at display variables)
https://waterrights.utah.gov/asp_apps/waterUseData/variableList.asp

**Comment by amabdallah** [comment]
This issue seems similar to this older one. Not sure if the data is the same and which one is easier to work with
https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/issues/42

**Comment by rwjam** [comment]
> Metadata (click at display variables)
> https://waterrights.utah.gov/asp_apps/waterUseData/variableList.asp

The metadata is slightly misleading, as it hints at variables that are not actually included in the download.  (e.g., there is no attached source data.  Only name / outcomes).

**Comment by rwjam** [comment]
> There is a download button for all data using CSV. Output unit should be either acre-feet or gallons (something to discuss)
> 
> Years range 1957-2019
> Data
> https://waterrights.utah.gov/asp_apps/waterUseData/setFilters.asp

The CSV approach returns both System and Source Data within the same CSV file (the Source portion is burred near the bottom).

The JSON approach appears to have an error in it and does not return the entire data set.  This might be something we should bring to their attention.

**Comment by rwjam** [comment]
Was able to map out and upload to our WaDE 2.0 system.  Few issues that need to be addressed, should do together in person when we have the time.

**Comment by amabdallah** [comment]
Let's revisit this one as it includes diversions to agriculture 

https://www.waterrights.utah.gov/cgi-bin/pubdump.exe

![image](https://user-images.githubusercontent.com/3268971/109216120-579f4e80-7771-11eb-837e-8da21a5476b7.png)

**Comment by rwjam** [comment]
Use this link: https://www.waterrights.utah.gov/cgi-bin/pubdump.exe?DBNAME=WRDB&SECURITYKEY=wrt2012access

**Comment by rwjam** [comment]
The data return is a link to a txt file.  The link doesn't look act like an API, it's just a return on service kind of thing.

The data itself is very dirty.
![image](https://user-images.githubusercontent.com/17555073/110038071-803cc080-7cfc-11eb-8a9c-4cf061e1c5f5.png)

**Comment by amabdallah** [comment]
Right, it is probably like an FTP service. Sure, we'd use the CSV file similar to exporting water rights data for UT

**Comment by rwjam** [comment]
data imported.

**Comment by rwjam** [comment]
Reopening this issue.

We would like to go back and update this data to also include agricultural & mining data.  For now keep it under the UT site-specific Public Supply Water Use data.
- Get data from [Water Use Data Portal (link)](https://waterrights.utah.gov/asp_apps/waterUseData/setFilters.asp).  It should contain all the timeseries for all beneficial uses.  The download merges System and Source data into the same tab, so you will have to separate the two manually.
    - if the data does not contain unique beneficial uses (particularly all the M&I and the new agricultural & mining data, take a look at this [API Variable Service (link)](https://www.waterrights.utah.gov/asp_apps/waterUseData/variableList.asp) here.
- Source data has lat & long site info to work with.
- For System data, try to relate to the [Utah Culinary Water Suppliers (link)](https://utahdnr.maps.arcgis.com/apps/webappviewer/index.html?id=050cace4aa4a43f5a38dbea00fb7f894) shapefile data.

**Comment by amabdallah** [comment]
Later next week, could you look if this data has a native URL that points to the state's data? If so, let's store it and also show it in the RShiny app. I've seen Utah landing pages for wells with historic records but not sure if they're available

**Comment by rwjam** [comment]
> Later next week, could you look if this data has a native URL that points to the state's data? If so, let's store it and also show it in the RShiny app. I've seen Utah landing pages for wells with historic records but not sure if they're available

One issue is that we don't have a way to store native URLs for sites / records in our ssps tables in WaDE at this time.  I can cheat for now with the RShiny app examples and just join that to the app data, just so we can see how that would work.
