### ISSUE TITLE
CO aggregate water supply data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#47]
https://data.colorado.gov/Water/DWR-Surface-Water-Supply-Index-Component-by-HUC/xbs6-xrne/data  

Contact: Brian Macpherson

**Comment by amabdallah** [comment]
This older issue talked about similar objective 
https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/issues/36

**Comment by amabdallah** [comment]
Something to investigate. 

1. The variable should be "supply"  instead of "consumptive use". 
2. The numbers seem way too high (20 M AF) i.e., more than the entire Colorado River annual flow. So careful attention is needed regarding how those numbers are aggregated.

![image](https://user-images.githubusercontent.com/3268971/107410696-dede9800-6aca-11eb-99b4-c95264c96b20.png)

**Comment by rwjam** [comment]
Looking at the source data, it could be how we are handling the Variable Type.

For that specific example (the Colorado Headwaters-Plateau), looks like a majority of the volume is coming form ForecastedRunoff.  We could eliminate that Variable Type and that would solve those high numbers.
![image](https://user-images.githubusercontent.com/17555073/107682162-31e85480-6c5d-11eb-9459-4b2a81c3f379.png)

**Comment by amabdallah** [comment]
Very interesting. We probably should keep this data but under the supply variable type and have three specific variables. The trick here is in visualization. Those three specific variables should not be added up. In this case, we want the variable specific plot to show them like the plot you have here.
How about we give the visitor the ability to choose which variable specific values they want to aggregate together to get them all in one plot (Variable plot)? like a check box selection. This is an interesting case for our portal.
