### ISSUE TITLE
UTssps Utah Retail Culinary Water Service Areas

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#50]
**Utah Retail Culinary Water Service Areas**

https://opendata.gis.utah.gov/datasets/1d2535e8c31247b9aaff664f6ac9c45d_0?geometry=-131.898%2C36.940%2C-91.216%2C42.682

**Comment by rwjam** [comment]
Site Specific data tents to involve points (e.g., lat & long).  This data uses polygons and areas.

**Comment by rwjam** [comment]
Use this link instead for Utah Culinary Water Service Areas: https://gis.utah.gov/data/utilities/retail-culinary-water-suppliers/

**Comment by rwjam** [comment]
We dediced to use this as ssps UT data, but use this issue instead: https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/issues/46
