### ISSUE TITLE
Import Idaho IDWR Site Specific Data

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#58]
Use this Site Specific Data portal for Idaho.  Data is in 'daily' values, so just place the same day in the timeframeStart & End field.

Link: https://research.idwr.idaho.gov/apps/hydrologic/aquainfo/

**Comment by rwjam** [comment]
ID data app is problematic.  Does not have 'get all' option.  Task will require to download / parse induvial csv together.

Task made harder as csv download does not include lat / long info, but info does exist on map.  Will require to down to manually add lat / long info to each download csv.

**Comment by amabdallah** [comment]
This comment relates to an email with @rwjam with the title: Extended contact names

------------------------
So after looking into the location data, there seem to be two fields that summarize the start and end date for each location (see the screenshot).
https://research.idwr.idaho.gov/apps/hydrologic/aquainfo/api/telemetry/locations

I tried changing the start and end date in the API call here and seems to work fine (obviously). The only challenge is related to how changing the date formate from their source to this needed one: YYYY-MM-DDTHH:mm:ss.sssZ

https://research.idwr.idaho.gov/apps/hydrologic/aquainfo/api/telemetry/99db207c15774d1c9a2f2a9daad85efa?fromDate=2019-09-21T14:33:47.134Z&toDate=2021-04-21T14:33:47.134Z

![image](https://user-images.githubusercontent.com/3268971/110363393-c09f8580-7fff-11eb-9f41-d743a912bcd6.png)






image.png

**Comment by amabdallah** [comment]
@rwjam was this done?
