### ISSUE TITLE
New Colorado site-specific reservoir and observation site data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#60]
@rwjam check out this Google doc that I wrote back in April 2019 about Colorado site-specific diversions data. It would be great if you can move its documentation once done to GitHub like the other states. I assume the links are still working
https://docs.google.com/document/d/1MiXYl7xaNCOqj5ulsv3BZBfUcXxnciGSPdkfk9D9nCM/edit

@tsga started this work here and I cannot find if there was code involved here. It was probably a manual processing and time-series data for just a couple of sites for testing purposes. @tsga, any recollection about this work? Thank you
https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/tree/master/Colorado/SiteSpecificAmounts

**Comment by rwjam** [comment]
Most of those links in the doc are outdated and no longer work.

The data available at the [above link](https://docs.google.com/document/d/1MiXYl7xaNCOqj5ulsv3BZBfUcXxnciGSPdkfk9D9nCM/edit) has no time stamp or volumetric values.

I believe this is the [water allocation table / data](https://data.colorado.gov/Water/DWR-Water-Right-Net-Amounts/acsg-f33s), but is that the type of data as time series site data?  Can we even make that comparison?

**Comment by rwjam** [comment]
This data might be a bit better. https://cdss.colorado.gov/gis-data

Looks it split
Division - South Platte  (1956, 1976, 1987, 1997, 2001, 2005, 2010, 2015)
Division 2 - Arkansas (1954, 1975, 1988, 1998, 2010, 2013-2018)
Division 3 - Rio Grande (1936, 1998, 2002, 2005, 2009 - 2019)
Division 4 - Gunnison (1936, 1998, 2002, 2005, 2009 - 2019
Division 5 - Colorado (1993, 2000, 2005, 2010, 2015)
Division 6 - Yampa/White
Division 7 - San Juan/Dolores

Sample image - Well for 2015 for South Platte and Arkansas.
![image](https://user-images.githubusercontent.com/17555073/102251560-3e049f80-3ec2-11eb-8d0a-91148048b90f.png)

**Comment by amabdallah** [comment]
> I believe this is the water allocation table / data, but is that the type of data as time series site data? Can we even make that comparison?

This one looks to be the water rights dataset. Not what we're looking for here.



> This data might be a bit better. https://cdss.colorado.gov/gis-data

Right! so looking inside, I found this: 
https://gis.colorado.gov/dnrviewer/Index.html?viewer=mapviewer
> DWR Map Viewer: All inclusive map viewer with over 170 map layers of DWR and CWCB data. (Use the Layer Catalog to add layers that are not pre-populated.) 

Try selecting these layers. Then see below how you can export the layers and their data into a shapefile. Then the last screenshot below seems to allow the query from an old API/form that goes back to 2007.  

![image](https://user-images.githubusercontent.com/3268971/102256584-cd14b600-3ec8-11eb-8950-cd45f96b3f91.png)


![image](https://user-images.githubusercontent.com/3268971/102256376-90e15580-3ec8-11eb-8c77-24b9b6b62e01.png)


![image](https://user-images.githubusercontent.com/3268971/102256704-eddd0b80-3ec8-11eb-8cc6-82054f85c988.png)

**Comment by amabdallah** [comment]
So I guess a good starting point would be to get the shapefiles and see the type of data/metadata they have. I'm sure they have a new API somewhere else where we can plug the station ID and parameters to query the time series data from it. CO folks are advanced on this.

**Comment by rwjam** [comment]
Found some time series data digging through the Colorado Map Viewer under the historic surface water condtions.  Might be tricky to try and automate all this.

- Surface Water Station (Historic) -> export to shapefile -> shapefile has sites, but has external link to timeseries data -> have to put in the request for time series data.

![image](https://user-images.githubusercontent.com/17555073/105765858-41099b80-5f16-11eb-89a3-35620853eda9.png)

**Comment by rwjam** [comment]
Was able to follow steps outlined above and view timeseries data for both Surface Water Current Conditions and Surface Water Conditions (Historic).  Each can provide a shapefile with site info, but acquiring time series data per site requires using a different surface.

Don't see a an API service / way to automate time series data retrieval just yet.

**Comment by rwjam** [comment]
'Might' have to use this [service](https://dwr.state.co.us/streamflow/), download timeseries for each site individual, then merge together using the 'USGSStateID -to- StationID'.

Doable, just time consuming.

**Comment by rwjam** [comment]
Loaded and pushed to QA.

**Comment by rwjam** [comment]
Remapped out this data.  Failed to include a waterclassNum unique search when getting data.  Resulted in sites having multiple values per year.

**Comment by rwjam** [comment]
Few Noted issues with the data

- We get our data from two different API services. The [first service (link)](https://dwr.state.co.us/Rest/GET/Help/Api/GET-api-v2-structures-divrec-waterclasses) we get our structures (sites).  Particularly, we are retrieving sites that have a divrectype = DivTotal, availableTimesteps = Year, and ciuCode = A (for active) values only.  We are only looking at records that have a divrectype = DivTotal, but other options include DivComment, DivTotal, RelComment, RelTotal, StageVolume, & WaterClass. I’m not sure which is which but I guess StageVolume might be more volume and stage info which we can maybe explore.  These are questions for CO who can hopefully explain what each type is.
- We get our timeseries info from the [second service (link)](https://dwr.state.co.us/Rest/GET/Help/Api/GET-api-v2-structures-divrec-divrecyear) here, using the wdid id from the first structure service to get all timeseries of matching wdid & waterclassNum field.
- For CO there is no indication if the flow data at a SiteTypeCV = reservoir is intake or outtake.  CO might be able to answer that question, but I don’t see anything in the metadata that could answer that for us.

**Comment by rwjam** [comment]
There is a WDID field tied to this data.  We could possible tie to this to water right information.
