### ISSUE TITLE
WA (WDNR) Watershed Administrative Units

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#61]
Let's look into adding these WAUs to our regulatory data

Watershed Administrative Units
https://geo.wa.gov/datasets/d8d2aeaa4cb24cca92b708b7ba086279/explore?location=47.239444%2C-120.817600%2C8.17

Looking more, I found this other data. 
WAECY - Water Resource Inventory Areas (WRIA)
https://geo.wa.gov/datasets/waecy::water-resource-inventory-areas-wria/explore?location=47.247796%2C-120.817600%2C8.43

**Comment by rwjam** [comment]
- Use this link instead for Watershed Administrative Units

**Comment by rwjam** [comment]
Uploaded and saved under WDNR
