### ISSUE TITLE
WA Current Streamflow Summary

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#62]
Let's look into adding the "River and streamflow monitoring" data starting from here. There does not seem to be a code-friendly way to get their data. So we probably need to discuss with their staff  
https://ecology.wa.gov/Research-Data/Monitoring-assessment/River-stream-monitoring/Flow-monitoring

Let's just focus on the "Ecology Daily Streamflow" layer. Let's ignore the USGS sites for now

![image](https://user-images.githubusercontent.com/3268971/98308395-2235e180-1f85-11eb-92e3-1bb230395fcf.png)

**Comment by rwjam** [comment]
There are charts for individual stream gages but no apparent way to download the data / mass download all the data from all gage stations.

**Comment by rwjam** [comment]
using new source data. closing this issue.
