### ISSUE TITLE
ND basin water use data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#64]
**Let's look into importing aggregate time-series water use data from ND**

Source
https://www.swc.nd.gov/info_edu/map_data_resources/waterpermits/waterusereport.php
I'll ask our contact there about allowing us to download all this data in a friendly way.

**North Dakota basins** 
The generated reports seem to have ~50 basins. I cannot find a map/shapefile for them. 

![image](https://user-images.githubusercontent.com/3268971/100018051-12960580-2d99-11eb-8010-8500a8db9d0f.png)

**Comment by rwjam** [comment]
- Saved excel copy of water usage report by basin grouped by use in the ND ag RawInputData folder.
- I "think" this is basin data to the HUC8 level.  There's a shapefile here https://gishubdata-ndgov.hub.arcgis.com/datasets/NDGOV::ndgishub-huc8-subbasin/explore?location=46.628502%2C-100.499197%2C7.35&showTable=true
-

**Comment by rwjam** [comment]
Use this link, the water use is buried in the water permits section: https://www.swc.nd.gov/info_edu/map_data_resources/
![image](https://user-images.githubusercontent.com/17555073/189688481-d4402bb7-948a-4c94-9324-c6253b7ef95f.png)

**Comment by amabdallah** [comment]
Was this dataset imported to the WaDE db? missing anything? or on the to-do-list? or just didnt make it to RShiy?
https://waterdataexchangewswc.shinyapps.io/AggregatedBudgetWaterUseDemo/
![image](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/assets/3268971/dc2df693-78d5-47a9-8430-51d7bd87266a)

**Comment by rwjam** [comment]
mapped to WaDE
