### ISSUE TITLE
Incorporate a general disclaimer into our water rights data per each state

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#65]
Water rights data are incomplete in many states and we need a legal disclaimer to show up for each state data on the dashboard. 
Ideally, we want to have a metadata column called: AgencyDisclaimer in the Methods Table. 
But for now, one way to share it is through the "Method Description", especially for water rights data.
In the portal, the disclaimer should show up as part of the metadata query.

**Example disclaimer by South Dakota**
https://danr.sd.gov/OfficeOfWater/WaterRights/Databases/WaterRights.aspx

**DISCLAIMER**. The above map dataset is incomplete. There are water permits/rights not included because coordinates for the location have not been established due to the lack of a proper legal description. This is often true of very old fillings that did not reference a specific section, township and range. Each water permit/right shown on the map is represented by a single diversion point (pumping location) even though the permit/right may have multiple diversion points. Most of the points shown on the map are calculated values and do NOT represent a precise location of the diversion point. Any reliance on the map results is solely at the user's discretion.

**Comment by amabdallah** [comment]
Let's add those disclaimers to the method table of each state water right data
Washington State disclaimer language https://fortress.wa.gov/ecy/gispublic/DataDownload/wr/GWIS_Data/GWIS_Data_Dictionary/disclaimer.html

**Comment by rwjam** [comment]
(01/27/2023 discussion) Let's go back and do the following.  We want to get more out of the Method.csv tables.  Need to track down more info per state.  This will require a little leg work and is not necessary directly tied to the location of the provided source water right data.

Let's map out our progress here: https://docs.google.com/spreadsheets/d/1E0GTwwUa8_w0ZUBNKMZNxm-jBx9QlfrQjirXL-rvk30/edit#gid=0

- For MethodDescription, let's split up with two paragraphs.  Lets include a paragraph that talks about the methodology of how the water right data was put together.  Lets include a second paragraph that uses the DISCLAIMER of the water right data.
- For MethodNEMILink, lets instead link to whatever unique water right processing / formation documentation the state has for how they determine what a water right is / put together.
- For MethodName, let's try to make that more intuitive and provide more info.
- For MethodTypeCV, if not given, let's just using the boilerplate value of "Legal Processes"


![image](https://user-images.githubusercontent.com/17555073/215160624-047e0360-c3fc-4ea6-aef2-661b5cff0835.png)
