### ISSUE TITLE
Import Alaska's water rights data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#71]
Let's study and map Alaska's water rights data and see what they have. I need to connect with the folks there before we import any data to the database. Alaska is not a full member of the Council right now and we need their approval before we import their data. We need to understand and map their data to WaDE so we can discuss any missing info in a call with them. I've imported their data before (from a spreadsheet they shared back then) to WaDE 1.0 but the folks we worked with back then have retired so we need to rebuild the relationship there. I also can share the spreadsheet they sent to us in 2018. 

There are old apps (see below) that have water rights data. But they also have a new ESRI Open Data Hub with water rights data as well. We should focus on the ESRI data source but it's worth looking into the old ones to understand any differences and if the new one missed any metadata we need.

**New data services**
This app seems to have surface water rights data points (Pt). I'm not seeing priority date or amount values here but they seem to exist if you click at the INFO_LINK hyperlinks. We probably need to download data from the old apps below and join them with this data. Not sure. We can ask them to add metadata to this new service but it will probably take a long time to get that added. 
https://gis.data.alaska.gov/datasets/water-right-surface-pt

**Alaska seems to have five categories of water rights (not fully sure).** 
This old app shows the water rights around the state. 
http://dnr.alaska.gov/mapper/controller?do=load_map&map_num=00006&gsid=8F3F05330D3900B1C4A1ECE646429A53.tomcat-91#map=5/-16416998.45/9242188.72

**This old site seems to support downloading a shapefile for the water right category (see below)**
http://asgdc.alaska.gov/#166

![image](https://user-images.githubusercontent.com/3268971/101052906-65fc1680-3544-11eb-8aa1-0c59ac2564fa.png)

![image](https://user-images.githubusercontent.com/3268971/101053000-8035f480-3544-11eb-859e-c883055375be.png)

**Comment by rwjam** [comment]
There is a 'download shapefile' option on the new site, but the resulting shapefile is scarce on useful information (i.e., missing ben use, priority date, source, etc).

![image](https://user-images.githubusercontent.com/17555073/105745023-10683880-5efb-11eb-952e-09563453aa6b.png)

**Comment by amabdallah** [comment]
Good! I'm wondering if the shapefile can be used for the spatial aspect and we get the rest of the data from a tabulated service.

**Comment by rwjam** [comment]
Seems like the older data was only pertinent to surface water data / it is also no longer available.

**Comment by amabdallah** [comment]
Check out this link. It provides their "permits" + water use data. It does have beneficial use data. See columns U and V in the water_data_usage.csv file: STATE_USE and WUC_CODE_DESC
This file is the same one that they shared with us in 2018 through email. It does not have long. and lat. So we need to join it to the shapefile.

https://dnr.alaska.gov/akwuds/

![image](https://user-images.githubusercontent.com/3268971/106020363-e93b7380-6080-11eb-8b52-94bedb59a7e8.png)

**Comment by amabdallah** [comment]
General info 
http://dnr.alaska.gov/mlw/water/rights/

**Comment by amabdallah** [comment]
TWUP: Temporary Water Use Permit – for a period less than five years, rather than granting a true water right.

TWUA: Temporary Water Use Authorization -- we’ve morphed the twup’s into twua’s, mostly just semantics—more recent permits are twua’s. (doesn’t roll off the tongue as well as twup does!)

LAS: Land Administration System, overall it is a database used to maintain and track permits across the state.  Prior to 1982, permits of all kinds from the state were given an ADL number (Alaska Division of Lands), now they are given an LAS number

**Comment by amabdallah** [comment]
Priority date included in this file as shared by Jim Vohden (retired now) at Alaska DNR on Feb 16, 2018
[AKWUDS download 30Jan18 with priority date.xlsx](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/files/5881610/AKWUDS.download.30Jan18.with.priority.date.xlsx)

**Comment by amabdallah** [comment]
For beneficial use, we need to concatenate two columns: STATE_USE -WUC_CODE_DESC

Concatnated   (STATE_USE -WUC_CODE_DESC) | Beneficial_use_code
-- | --
Water Supply - Public   (Municipal) Community | WSPC
Fish & Wildlife - Research   & Conservation | FWRC
Oil & Gas - Petroleum   Refining | OGPR
Commercial - Retail/Wholesale | CRW
Oil & Gas - Ice Roads and   Pads | OGIRP
Fish & Wildlife - Zoo | FWZ
Oil & Gas - Operation | OGO
Operation | O
Oil & Gas - Pipeline | OGP

**Comment by amabdallah** [comment]
Shapefile metadata
http://dnr.alaska.gov/mdfiles/wr_surf.html

![image](https://user-images.githubusercontent.com/3268971/106024187-c14e0f00-6084-11eb-9b2f-b0d256185d05.png)

**Comment by rwjam** [comment]
This data and links are out of data.  Closing issue with plans on replacing with a more update to date issues, links & notes.
