### ISSUE TITLE
Oklahoma Surface Water Data, Standards & Protection data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#73]
Let's look into importing the Oklahoma regulatory boundaries

**1. Start here to get to know things: this source here shows the different types of regulations but it does not allow exporting the layers.**
https://owrb.maps.arcgis.com/apps/webappviewer/index.html?id=148c632a75db48ac92470290c7382bad
![image](https://user-images.githubusercontent.com/3268971/102145016-c7b16000-3e23-11eb-9160-e8025f7bf3bd.png)

**2. Look here for the source of data that can be downloaded. We want to import this layer to WaDE. Check out the "10 Layers" button to see the metadata** 
https://home-owrb.opendata.arcgis.com/datasets/surface-water-standards/data?geometry=-119.461%2C32.135%2C-77.648%2C38.408&layer=9

![image](https://user-images.githubusercontent.com/3268971/102145515-9be2aa00-3e24-11eb-99a5-71707f7f053e.png)

**Comment by rwjam** [comment]
Data mapped and submitted to QA.  Water rights updated for ReportingUnitCVs.
