### ISSUE TITLE
Import California Public Drinking Water Systems data to WaDE

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#75]
**See the comment on this issue below and ignore the data in this first one.**

California Water Boards publishes their Public Drinking Water Systems data each year in a huge flat file [see EAR Reporting Years (RY)]. Each file is so big that it has 10 columns wide and 4 to 8 million records tall. So it needs to be handled in Pandas (?) or a library that deals with that huge number of rows. You probably can load it into an SQLite table within Python.
You can view the data in Excel by importing the text file but it won't load completely because Excel cannot handle that many rows. The reason it is so big is that there are 1,037 fields of data (pivoted horizontally) for each "Water System." I'm positive this is a view table that joins so many tables in their back-end database. We're just interested in a small subset of those fields. See their data dictionary and water system inventory files below. I think we still need a shapefile to get the location of these water systems (centroid of now)
 
To simplify things, we probably should start with annual values such as: "WP   Annual GW" and " WP Annual SW"

https://www.waterboards.ca.gov/drinking_water/certlic/drinkingwater/eardata.html

![image](https://user-images.githubusercontent.com/3268971/107566008-904ffd00-6ba1-11eb-9840-ee2fb5b84017.png)

![image](https://user-images.githubusercontent.com/3268971/107575172-d199da00-6bac-11eb-8f44-1e070f34fb9a.png)

**Comment by amabdallah** [comment]
Wait! There seem to be better (smaller) data sources 

https://data.ca.gov/dataset/drinking-water-public-water-system-information

https://data.ca.gov/dataset/drinking-water-public-water-system-annually-reported-water-production-and-delivery-information

**Shapefile**
https://gis.data.ca.gov/datasets/fbba842bf134497c9d611ad506ec48cc_0/data?geometry=-160.357%2C31.280%2C-76.729%2C43.454

**Comment by rwjam** [comment]
Going to use both Produced Water & Delivered Water data, and pair both to the Area of Use as POU.
Produced Water = Produced Water variableCV.
Delivered Water = Delivered Water variableCV.

**Comment by amabdallah** [comment]
Rafa Maestu at CA Control Boards responded to my question if they have PODs data for each POU:

> We don't have (yet..) a cross reference table of PWSID and POD.. in many cases we don't even have a good cross reference of Well ID and PWSID.. We need to make it a priority.. keep asking, please. Yes please.. send us an email with the question... and we can forward it to the programs
