### ISSUE TITLE
Import TCEQ water rights data into WaDE

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#8]
**See Active water rights file**
https://www.tceq.texas.gov/permitting/water_rights/wr-permitting/wrwud

**See the data dictionaries in PDF and these attached TXT files** 

[LU_BENEFICIAL_USE.txt](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/files/3969634/LU_BENEFICIAL_USE.txt)
[LU_CLASS_CODE.txt](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/files/3969636/LU_CLASS_CODE.txt)
[LU_SOURCE_TYPE.txt](https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/files/3969639/LU_SOURCE_TYPE.txt)

**See Surface Water Rights Diversion Points at the bottom of the page above:** (I'm guessing we need to join this GIS data with the water rights data in Excel.
GIS data for locations of water rights.

**Comment by tsga** [comment]
The following link has a design document I working on the mapping of the TX allocations to WaDE. I couldn't do the coding at this time because I couldn’t establish mapping between water rights and sites, i.e., couldn’t find out the connection between water rights data (wractive.xlsx) and the POD data (TexasWRShapes.csv ) extracted from GIS files.

https://drive.google.com/open?id=1-0Y_gLuBJpAtiWcgpbnfbdXax1uILKA3sEpdFf4m-gM

**Comment by amabdallah** [comment]
@tsga could you please post the TexasWRShapes.csv/POD data file into Google Drive? I'd like to see its attributes. 

Looking at the wractive.xlsx file, it does not have a unique identifier for water rights. Right? that's likely an issue for joins.

Let's discuss this data mapping on Thursday or Friday this week so I can send an email to the folks over there.

**Comment by amabdallah** [comment]
@tseg Based on this doc,https://www.tceq.texas.gov/assets/public/permitting/watersupply/water_rights/applications/ddiction_new_wractive.pdf

WR NO seems to be the identifier. I'm guessing now that the POD data does not have this identifier which explains the issue you described above.

**Comment by tsga** [comment]
@amabdallah there is a field “WR_NO” both in “wractive.xlsx” and “TexasWRShapes.csv”, but in the “TexasWRShapes.csv” “WR_NO” is mostly blank and when there is value in this column, the values in the other columns for water rights are empty.

**Comment by amabdallah** [comment]
Only "Rio_Grande_unverified_WaterRights" shapefile layer has mapping to the Water rights file.

**Comment by amabdallah** [comment]
TCEQ has a new way of sharing water rights data. So we're closing this issue and starting another one for the new data
