### ISSUE TITLE
NV Aggregated Data

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#87]
Import the 2015 and 2017 county and basin inventory Pumpage records for NV (see local shapefiles) aggregated data.

Data is the aggregate of withdrawal from wells.  Groundwater.  Acre-feet.  See Metadata within shapefile (in AcrGIS PRO) for more methodology info.

Data Link.  http://water.nv.gov/gisdata.aspx

![image](https://user-images.githubusercontent.com/17555073/117210747-557eef00-adb5-11eb-8384-111a37b12aa1.png)

**Comment by rwjam** [comment]
Data mapped out and pushed to QA.  Consist of POD withdrawal sites for County and river basin reporting unit area types.

**Comment by amabdallah** [comment]
Let's import Nevada's aggregate data from this data source for Basins.  Let's add a new variable called ~: commitments. I think commitments are the aggregate permitted water use per category in each county or basin. 
https://www.arcgis.com/apps/webappviewer/index.html?id=a5c7956f02f84d53bb8746672e63fe31

**Comment by rwjam** [comment]
Use this link instead: https://data-ndwr.hub.arcgis.com/apps/NDWR::nevada-water-use-map-1/about
