### ISSUE TITLE
"Wild and Scenic River" beneficial use mapping to WaDE Terms

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#93]
There will be a workshop on "[Wild and Scenic Rivers](https://hub.arcgis.com/datasets/usfs::national-wild-and-scenic-river-line/explore?location=35.672760%2C-97.123896%2C4.99)" as part of the Fall 2021 Council Meetings in South Dakota. 
Looking into our beneficial uses, I found that CA and ID recognize "Wild and Scenic Rivers" as a beneficial use which is great. I'm not sure why other states don't have that designation but it's something to watch for.  It's probably an ongoing process.
https://docs.google.com/spreadsheets/d/1tZ3DIYDx7J-dsldHfihQjOABibMpFoGKvmSe8ReKW10/edit?usp=sharing

For now, we need to update the WaDE term from "Wildlife" to probably be "Wild and Scenic Rivers" or just "Instream Flow" , "Fish and wildlife" which we already have. I'm not sure how the Azure CVs workflow updates our QA database after we make this little change.
 
I'm curious if other states are using other environmental, aquatic, or instream flows instead of "Wild and Scenic Rivers". We'll have to ask each of our member states about this.  
![image](https://user-images.githubusercontent.com/3268971/124816649-fad55100-df25-11eb-9dc3-c8aa68a5d267.png)

**Comment by rwjam** [comment]
This might be an issue that can be solved by utilizing the existing  **AllocationTypeCV** or **LegalStatusCV** fields in WaDE, and just calling it the _Wild and Scenic Rivers_.

**Comment by rwjam** [comment]
Some of this ties into WYwr data. Their "beneficial use" is like scared from their legislative's perspective and they cannot touch it. So they added Prefix and Suffix separate fields to add context.  For WY, the intent is that we use the suffix metadata to help us map their beneficial use to WaDE controlled voab beneficial use as we have the freedom to so while still pointing to their original term.

We need to update the WY water right beneficial use to include a “Wild and Scenic River” value.  Use the suffix metadata, and anything with a Z in it also has a beneficial use = Wild and Scenic River
