### ISSUE TITLE
MT Streamgage locations and data

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#95]
We provided a small grant to MT to help them share their stream gage data (i.e., discharge and stage variables). The product is here 
https://gis.dnrc.mt.gov/apps/StAGE/#

I clicked around and found different ways to access the data. Here is the "gage reports page". I'm not sure if there is a programmatic way to get the data through.
https://gis.dnrc.mt.gov/apps/stage/gage-report/

I was able to save the GIS layer to the WSWC account here. So hopefully now we have access to the shapefile and metadata. 
https://wswc.maps.arcgis.com/home/webmap/viewer.html?webmap=d406c7c4be304a90b93e65564e4897ba

As a starter, let's get the metadata tables ready, especially the "sites" one. Then import data for a couple of sites. In the end, we need to come up with a list of questions to ask MT DNRC to help us fully import the data to WaDE.

Although WaDE time series data focuses on monthly time steps as its most common in our states, we should import this daily data.

**Comment by rwjam** [comment]
Was able to to convert some of the available Feature Classes -> workable tables from the GIS layer.

Matching site ID fields don't exist between location & timeseries info. But we should be able to extract some timeseries data from the **WWM StAGE - timeseries** layer and link it to the **WMB StAGE - locations** layer if we use the **WMB StAGE - datasets** layer as a bridge table.

**Comment by rwjam** [comment]
Map these out, and fill out the 'Data Irregularities' folder and documents.

We DO want to reach out to MT and ask for assistance / guidance, but better to only do it once once everything.

**Comment by rwjam** [comment]
Data mapped out and imported into WaDE.
- Only working with ParameterLabel = Discharge, ComputationMethod = Mean, & ComputationPeriod = Daily values for now.
- 120 usable surface water gage sites
- 274,807 timeseries records

**Comment by rwjam** [comment]
On the topic of why some MT sites for reservoir level data are not labeled as site type=reservoir...

- Unfortunately, the provided native SiteTypeCV for all MT sites is labeled as ‘Hydrology Station” (see image). MT did not specifically call these locations out as reservoirs.  We could manually label these site with a SiteTypeCV of reservoir as we know they are part of a Reservoir Level VariableCV data type, but that would be making assumptions and taking ownership of their data and not relaying the provided state information.

![image](https://user-images.githubusercontent.com/17555073/206808620-ab02ab56-ef36-4585-ac26-70b7495870ab.png)
