### ISSUE TITLE
Import Kansas Ground Water Management Districts

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#97]
I can't find a shapefile for them. If you find one or many, please post the link as a comment

http://www.kgs.ku.edu/Hydro/gmd.html

**Comment by rwjam** [comment]
Did find some downloadable shapefile from the Data Access and Support Center (DASC) site: https://kansasgis.org/index.cfm

![image](https://user-images.githubusercontent.com/17555073/134558011-92f843b4-ffed-4c74-8bbe-20308fbcae0b.png)
![image](https://user-images.githubusercontent.com/17555073/134558075-8699d01f-0719-4760-b4eb-ad059aece265.png)

**Comment by rwjam** [comment]
mapped to WaDe.
